Veil-Project/veil

src/qt/veil/toast.h
=> fix guards to reflect filename

src/init.cpp, src/util.cpp
Copyright information now includes PIVX, Bitcoin, Particl and other developers
=> Update Copyright Data

src/chainparams.cpp
Pretty straight forward; adds support for the two DNS Seeder servers I'm running
=> [Net] Add fuzzbawls DNS seeders

src/qt/veil/forms/settingsminting.ui, src/qt/veil/forms/settingsrestoreseed.ui, src/qt/veil/forms/settingswidget.ui, src/qt/veil/settings/settingsfaq01.cpp, src/qt/veil/settings/settingsfaq04.cpp, src/qt/veil/settings/settingsfaq05.cpp, src/qt/veil/settings/settingsfaq06.cpp, src/qt/veil/settings/settingsfaq07.cpp, src/qt/veil/settings/settingsfaq09.cpp, src/qt/veil/settings/settingsfaq10.cpp, src/qt/veil/settings/settingsfaq11.cpp
Made changes to accompanying .cpp files for .ui recent accompanying changes.
Made some additional changes to some settings .cpp and .ui files to fix spelling errors and the like.
=> Additional updates to ui text to supplement last pr.

src/qt/veil/forms/mainwindow.ui, src/qt/veil/forms/veilstatusbar.ui, src/qt/veil/mainwindow.cpp, src/qt/veil/veilstatusbar.cpp
closes https://github.com/Veil-Project/veil/issues/29
=> GUI: staking status slider icon / object name

src/consensus/tx_verify.cpp, src/interfaces/wallet.cpp, src/interfaces/wallet.h, src/miner.cpp, src/qt/sendcoinsdialog.cpp, src/qt/walletmodel.cpp, src/qt/walletmodel.h, src/script/ismine.cpp, src/validation.cpp, src/veil/ringct/anonwallet.cpp, src/veil/ringct/anonwallet.h, src/veil/ringct/outputrecord.cpp, src/veil/ringct/outputrecord.h, src/veil/ringct/rpcanonwallet.cpp, src/veil/ringct/stealth.cpp, src/wallet/wallet.cpp
Spend type priority (determined by whether balance can cover the tx)
1: zerocoin
2: RingCt
3: CT
=> GUI spend dialog automatically uses most private spend type.

src/wallet/wallet.cpp
- The current code only checks for ringct when trying to mint zerocoin, this fix now checks for both ringct and ct and fails the mintzerocoin call if both types fail to add inputs to the transaction.
=> Allow ct to be converted to zerocoin

src/miner.cpp
- While investigating the return values for the rpc call **getblocktemplate** it was difficult to determine the reasoning for some failures. 
This PR fixes this issue by adding more visibility to the failures that the rpc call can return.
=> Add some failure checks to getblocktemplate call

src/policy/policy.cpp
=> Update Standard Inputs to Skip Anon Inputs

src/qt/forms/addressbookpage.ui, src/qt/forms/sendcoinsentry.ui, src/qt/sendcoinsdialog.cpp, src/qt/sendcoinsentry.cpp, src/qt/sendcoinsentry.h
=> [QT] send to addressbook contact button and dialog

src/validation.cpp
Use batch verify for zeroknowledge proofs in ConnectBlock(). This significantly reduces the time it takes to validate a block.
=> [Consensus] Batch verify zeroknowledge proofs per block

src/test/monthly_rewards_tests.cpp, src/veil/budget.cpp, src/veil/budget.h
Testnet super blocks on height 20'000 (mod `nBlocksPerPeriod`).
Next one scheduled in about 4 days from now.
Fix unit-test.
=> [Consensus] change superblocks schedule for test-net

src/qt/coincontroldialog.cpp, src/qt/coincontroldialog.h, src/qt/forms/coincontroldialog.ui, src/qt/optionsmodel.cpp, src/qt/sendcoinsdialog.cpp, src/qt/sendcoinsentry.cpp, src/qt/transactionrecord.cpp, src/qt/walletmodel.cpp, src/veil/ringct/anonwallet.cpp, src/veil/ringct/outputrecord.cpp, src/veil/ringct/rpcanonwallet.cpp, src/veil/ringct/temprecipient.h, src/wallet/coincontrol.h, src/wallet/rpcwallet.cpp, src/wallet/test/coinselector_tests.cpp, src/wallet/wallet.cpp
The code seems to work on face and updates values properly. I still have to test if using the dialog sends the correct coins.
(fixes #111)
=> Coin control dialog for CT and RingCT

src/veil/ringct/anonwallet.cpp
It now distinguishes between spendable and immature ct and ringct. I've tested minting zerocoin with unconfirmed ringct; it switches to using ct instead of ringct.
(fixes #301)
=> Add confirmation check to CT and ringCT balance

src/qt/forms/overviewpage.ui
Changed btnGoFaq from minimum width of 205px to 235px
(fixes #330)
=> Fix issue #328

src/qt/addressbookpage.cpp
=> fix for issue #323

src/wallet/rpczerocoin.cpp
Changed maximum zerocoins per spend in the RPC_WALLET_ERROR to 20
=> Updated "construct JSON to return"

src/wallet/rpczerocoin.cpp
Closes https://github.com/Veil-Project/veil/issues/350
=> [RPC] add check for security level value in spendzerocoin

src/qt/modaloverlay.cpp, src/qt/modaloverlay.h
=> [QT] Modal overlay opaque background force resize on every show.

src/veil/ringct/anonwallet.cpp, src/wallet/rpcwallet.cpp, src/wallet/wallet.cpp, src/wallet/wallet.h
- Return change from a basecoin zerocoinmint to CT change address.
- If adding a wtx to mempool, return an error if it failed.
closes #271
=> [Wallet]Change basecoin mint to return change as CT

src/wallet/rpczerocoin.cpp
- use serial hash (instead of pubcoin hash) for non-verbose output as that is the data required by `spendzerocoinmints`
- sort the output by descending confirmations number
=> [RPC][Zerocoin] update listmintedzerocoins

src/qt/res/css/main.css, src/qt/veil/addresseswidget.cpp, src/qt/veil/forms/settingswidget.ui
Settings form: Update font size of menu item to match. 
Address book listing: Update font size of address label and address to match. 
closes #325
=> [Wallet] [QT] Standardize font size on settings form and address book listing

src/Makefile.am, src/Makefile.qt.include, src/httprpc.cpp, src/init.cpp, src/init.h, src/interfaces/node.cpp, src/miner.cpp, src/qt/bitcoingui.cpp, src/qt/splashscreen.cpp, src/qt/splashscreenveil.cpp, src/qt/test/test_main.cpp, src/qt/veil.cpp, src/qt/veil/veilstatusbar.cpp, src/qt/veil/veilstatusbar.h, src/rpc/misc.cpp, src/rpc/rawtransaction.cpp, src/validation.cpp, src/veil/proofofstake/kernel.cpp, src/veil/proofofstake/stakeinput.cpp, src/veil/ringct/rpcanonwallet.cpp, src/veil/zerocoin/accumulators.cpp, src/wallet/init.cpp
=> Fix crash with -disablewallet

src/primitives/transaction.cpp
- Quick fix for scriptsig zerocoin check
=> Add scriptsig zerocoinspend check

CMakeLists.txt, src/miner.cpp, src/qt/res/css/main.css, src/qt/veil/forms/veilstatusbar.ui, src/qt/veil/settings/settingsminting.cpp, src/qt/veil/veilstatusbar.cpp, src/qt/veil/veilstatusbar.h, src/qt/walletmodel.cpp, src/qt/walletmodel.h, src/qt/walletview.cpp, src/txdb.cpp, src/veil/ringct/anonwallet.cpp, src/wallet/rpcwallet.cpp, src/wallet/rpczerocoin.cpp, src/wallet/wallet.cpp
=> Connect GUI and RPC to wallet unlockforstaking only flag.

src/qt/overviewpage.cpp
Update sizeHint to adjust widget height based on current DPI
Update text rect to adjust width by inner font length
closes #354
=> [Qt] Change transaction listing to scale with DPI

src/qt/veil/updateaddress.cpp
fix issue #556
Redone since the first one was updating another file which was correct before fixing
=> UI - textchange fix - correct error in first PR

src/interfaces/wallet.cpp, src/interfaces/wallet.h, src/qt/signverifymessagedialog.cpp, src/rpc/misc.cpp, src/wallet/rpcwallet.cpp
=> Provide Signature/Verification facility with Stealth addresses.

src/chainparams.cpp, src/qt/walletmodel.cpp, src/qt/walletmodel.h, src/veil/ringct/anonwallet.cpp, src/wallet/wallet.cpp
- The change wasn't being calculated correct when adding zerocoin mints as change
- Added checkout into testnet for quicker sync. 
Fixes #489 Fixes #458
=> [Wallet]Fix change amount when minting zerocoin as change

src/qt/forms/optionsdialog.ui
Also Fix the tool tip color.
Fixes #240
=> Make the push buttons in Advanced Preferences look more "clickable"

src/chainparams.cpp
- Add params values that allow for blocks to be mined on regtest
Closes #561
=> Fix regtest chainparams

src/qt/bitcoingui.cpp, src/wallet/wallet.cpp
Also Show reindexing percentage on status bar.
Fixes #475 
Fixes #476
=> [Qt] Show rescanning percentage on splash screen.

src/interfaces/wallet.cpp, src/interfaces/wallet.h, src/miner.cpp, src/qt/forms/optionsdialog.ui, src/qt/optionsdialog.cpp, src/qt/optionsdialog.h, src/qt/sendcoinsdialog.cpp, src/qt/transactionrecord.cpp, src/qt/transactionrecord.h, src/qt/veil/forms/transactiondetaildialog.ui, src/qt/veil/transactiondetaildialog.cpp, src/qt/walletmodel.cpp, src/qt/walletmodel.h, src/veil/ringct/rpcanonwallet.cpp, src/wallet/rpcwallet.cpp, src/wallet/wallet.cpp, src/wallet/wallet.h
- Adds "Show compute time" setting to Wallet Options Dialog
- Adds Compute Time to Wallet Transaction Record and Transaction Details Dialog 
Closes #460
Bounty payment address:
sv1qqp0j5cm6vrrkvkajpnq39gczt09eclw5z8h2zrmvrwndw7ppqaa28spqfqmkpana500t0jmjnhcjekg0rgt9jfll3w03m46p7ard9lqrpxduqqqe9a2qv
=> [Wallet] Add Transaction Compute Time

src/miner.cpp
Do one last double check in the miner for transactions that overwrite other transactions.
=> [Miner] Filter out BIP30 enforced tx from new blocks.

src/consensus/tx_verify.cpp
closes #547 
`CheckZerocoinMint()` can be done from different threads at the same time. Lock static containers. If try_lock fails, don't wait, just do full validation. Issues were arising when two threads were modifying the static containers at the same time.
=> [Validation]Lock CheckZerocoinMint()

src/qt/veil/forms/settingsminting.ui, src/qt/veil/settings/settingsminting.cpp
Also disable the mint button in this scenario.
Fixes #226
=> [Qt] Add warning label if zero coin balance is less than minimum.

src/wallet/rpcwallet.cpp
Adding `getspendablebalance` RPC Call.
- Returns the combined total of all spendable coins.
Closes #496 
Bounty Address
```
```
=> [RPC]Adding `getspendablebalance` RPC Call.

src/qt/veil/balance.cpp, src/qt/veil/balance.h, src/qt/veil/tooltipbalance.cpp
=> [Qt] Add mouse leave event to balance buttons.

src/veil/zerocoin/zwallet.cpp, src/veil/zerocoin/zwallet.h, src/wallet/rpczerocoin.cpp
Move Deterministic Zerocoin Search threading to zWallet
Add DeterministicSearch progress indication
Closes: #552 
payment address:
sv1qqp0j5cm6vrrkvkajpnq39gczt09eclw5z8h2zrmvrwndw7ppqaa28spqfqmkpana500t0jmjnhcjekg0rgt9jfll3w03m46p7ard9lqrpxduqqqe9a2qv
=> [Wallet] searchdeterministiczerocoin progressbar

src/qt/veil/forms/transactiondetaildialog.ui, src/qt/veil/transactiondetaildialog.cpp, src/qt/veil/transactiondetaildialog.h
=> [Qt] Add hyperlink for txid in transaction detail view.

src/validation.cpp
Make sure that zerocoinspends that are less than version 4 do not make it into the mempool.
=> Reject < v4 zerocoin from mempool.

src/qt/modaloverlay.cpp, src/qt/overviewpage.cpp, src/qt/sendcoinsdialog.h, src/qt/transactionrecord.h, src/qt/veil/addressesmenu.cpp, src/qt/veil/addresseswidget.cpp, src/qt/veil/addressnewcontact.cpp, src/qt/veil/addressreceive.cpp, src/qt/veil/balance.cpp, src/qt/veil/receivewidget.cpp, src/qt/veil/settings/settingsminting.cpp, src/qt/veil/settings/settingsrestore.cpp, src/qt/veil/settings/settingsrestorefile.cpp, src/qt/veil/settings/settingswidget.cpp, src/qt/veil/tooltipbalance.cpp, src/qt/veil/tutorialmnemonicrevealed.cpp, src/qt/veil/updateaddress.cpp, src/qt/veil/veilstatusbar.cpp
* Trivial fixes of ctor initialization order.
For issue #719
=> Lint:  initialization order issues.

src/qt/veil.cpp
This takes care of a Qt issue on more recent versions.
fixes: #710
=> [Qt] AADPI fix - Enables high-DPI scaling in Qt on supported platforms

src/libzerocoin/bignum.h
* This was included indirectly from elsewhere previously.
* Fixes our Travis builds.
=> include for CHAR_BIT.

contrib/veil-cli.bash-completion, src/chainparams.cpp, src/chainparamsbase.cpp, src/chainparamsbase.h, src/init.cpp, src/net_processing.cpp, src/qt/guiconstants.h, src/qt/guiutil.cpp, src/qt/locale/veil_en.ts, src/qt/networkstyle.cpp, src/qt/paymentserver.cpp, src/qt/veil/transactiondetaildialog.cpp, src/test/key_io_tests.cpp, src/util.cpp, src/util.h, src/validation.cpp, src/veil-cli.cpp, src/veil-tx.cpp, src/veild.cpp, src/version.h
Creates are new network for testing changes.
To launch the devnet arg: -devnet
**Other details** 
Folder: devnet
Port: 58812
=> [Net] Create devnet an alternative testnet

src/qt/veil/addresseswidget.cpp
* don't include .cpp files. correct one instance of this.
=> [Refactor] Don't include cpp files.

.travis.yml
=> [Build] Leave 30 minutes for the full build, instead of 20

src/rpc/mining.cpp
- instead of switch headers every rpc calls give the GPU miners 1 minute to solve the header
=> Allow for caching of local mining headers

src/rpc/server.cpp, src/wallet/rpcwallet.cpp
* Wrong port.
* Wrong syntax in getspendablebalance.
=> [TRIVIAL][RPC] Fix RPC related typos.

.github/workflows/build-factory.yml, .travis.yml, configure.ac, src/Makefile.am
Merge Github Actions to v1.1.0 branch
=> [WIP][Build] Created Github Actions CI for Veil

.github/workflows/build-factory.yml, configure.ac, src/Makefile.am, src/crypto/randomx/argon2.h, src/crypto/randomx/argon2_avx2.c
Work in Progress.  Separated a64 and x86_64 jit components
=> [WIP][Build] Update for ARM builds

src/chainparams.cpp, src/miner.cpp, src/pow.cpp
- Fixed regtest parameters
- Fixed nVersion setting a bit that is now the RandomX bit
- Squash a division by zero issue
- debug message nit
will be merged after github action pass
=> Fix Regtest + more

src/miner.cpp, src/pow.cpp, src/pow.h, src/rpc/mining.cpp, src/validation.cpp
`checkproofofwork()` was still checking to make sure the target was less than the X16RT PoW limit, and not checking against the PoW limit for the algo being mined.
Fix it.
=> [PoW] Correct difficulty limit checks

src/miner.cpp
Shutting down progpow and randomx mining hangs
- ProgPow: Interruption point was missing in the inner loop
- RandomX: When shutting down RandomX mining before it's fully up and running, there isn't an internal mining thread yet but the external thread exists.  In this situation, the external thread would not be interrupted when shutting down or stopping randomx mining.
- Fix 'em
- Include division by zero fix during the randomX thread
- Remove stale randomX code in general mining thread
- Ensure the general mining thread shuts down if being asked to mine an unsupported mining type
- Ensure the general mining thread doesn't mine X16RT after the fork
- Clean up some debog logging.
=> [PoW] Correct randomx stop and progpow thread interrupt

src/qt/veil.cpp
With the Qt wallet and an invalid mining address, the user isn't notified on startup and with mining scripts, won't see the error message from getblocktemplate.
The Qt wallet uses different startup flag processing.  While ParseParameters() provides a centralized common method to check the mining address; it's pulled in by all the executables (-tx, -cli, d and -qt), and the miningaddress check needs too much infrastructure to be pulled into -tx and -cli).  It also needs the global parameters to already be setup to function properly.  As such, the only one checking on startup was veild.
Add similar code to Qt, in such a way that it's being called after everything required is setup, and not in such a way that it effects the module dependencies of veil-tx or veil-cli
Bad address creates a pop …
=> [GUI] Disallow stealth mining addresses

src/rpc/mining.cpp, src/validation.cpp, src/validation.h
=> disable algo-check on blockcreate, add mining state to getblocktemplate

src/pow.cpp
PoS blocks were falling behind their allotted slots due to increases in ProgPow hash power.
A few problems existed.  The first was that the desired timespan for the PoS difficulty adjustments was based on the 120th PoS block back to the current tip; but the actual was calculated from the 120th PoS block back to the latest PoS block.  So if the latest block was not PoS, then the actual timespan in the calculation would be shorter then it actually was, and therefore the PoS difficulty wouldn't adjust where it should adjust to.
Secondly, the PoS difficulty was being based on a fixed spacing value, when it's actually dynamic.  When all PoW algos are running with enough hash power to maintain their spacing, then the PoS separation should be 120 seconds between blocks.  However, when algos hit …
=> [PoS] Fine tune PoS difficulty adjustments

.github/workflows/build-factory.yml, configure.ac, src/Makefile.am
RandomX build issues on 32 bit systems
64 bit code was pulled in, either arm or x86.  Re-work build to only build a64 for 64, and x86_64 as appropriate
github action build of 32 bit linux x86 still fails due to dependency issues, but the others are working.  This may be merged as is and the last one [commented out] for later.
Note:  It's not been run yet with the commented out yml, so that might need a tweak
=> [WIP][Build] Fix randomx build on 32b systems

src/net_processing.cpp, src/version.h
Update protocol version with current mainnet and future mainnet versions
=> [Chain] Change min peer proto rules

src/chainparams.cpp
Setting the current targeted fork dates:
testnet: 11:59:59PM GMT - October 13th 
mainnet: 05:00:00PM GMT - October 31st
=> [Chain] Set fork dates

.github/workflows/build-factory.yml, CONTRIBUTING.md
i686 Linux 32 Github Action was failing
#857 and add a ton of package re-installs for some weird reason
This PR also includes the #857 change
=> [CI][Build] Reinstate i686 Linux 32 Github Action

.github/workflows/build-factory.yml, CONTRIBUTING.md
=> [Build] Reinstate i686 32bit linux build

src/chainparams.cpp, src/chainparams.h, src/miner.cpp, src/net_processing.cpp, src/policy/policy.h, src/validation.h, src/version.h
Add height checks so current v1.2 dev build will run on mainnet.  Also start removing the fork checks for PoW mining.
=> [PoS] Add height checks to be able to run on mainnet

depends/packages/qt.mk
Temporary tweak of qt package dependency for Actions to function.
=> [Build] temporary tweak of qt package

src/qt/forms/overviewpage.ui
New users don't have enough information to get the wallet synced.
Provide the information.
=> [GUI] Update wallet overview with coin and wallet information

src/qt/transactionrecord.cpp
When dealing with some orphan transactions, some addresses aren't in the address map, and so when we look them up we get an invalid return value to indicate we didn't find it. 
Verify the address is valid before trying to get the boost value.
Windows 10 testnet wallet.
=> [QT] Proposed fix for (one type of) force_return errors

contrib/gitian-descriptors/gitian-linux.yml, contrib/gitian-descriptors/gitian-osx.yml, contrib/gitian-descriptors/gitian-win.yml
Gitian build file changes needed to support c++17 and OSX
=> [Build] build changes for c++17 and OSX

contrib/devtools/symbol-check.py, contrib/gitian-descriptors/gitian-linux.yml
Updated check symbols script for c++17
=> [Build] Updated check symbols script for c++17 

src/qt/forms/overviewpage.ui
=> [GUI] Set minimum scrollbar height for transactions history list

.github/workflows/build-factory.yml
Reference: https://github.com/Veil-Project/veil/pull/1026
Removed **ppa:bitcoin/bitcoin** from build-factory.yml to fix build-i686-linux32 step
Replaced apt-get with apt
=> Removed ppa:bitcoin/bitcoin from build-factory.yml

depends/packages/gmp.mk, depends/packages/qt.mk, depends/packages/zlib.mk
Changed unavailable urls to our mirror for:
- libgmp
- zlib
- qt
=> Fixed build
