Veil-Project/veil

src/qt/veil/forms/settingsfaq.ui
src/qt/veil/forms/settingsfaq04.ui
src/qt/veil/forms/settingsfaq05.ui
src/qt/veil/forms/settingsfaq06.ui
src/qt/veil/forms/settingsfaq07.ui
src/qt/veil/forms/settingsfaq08.ui
src/qt/veil/forms/settingsfaq09.ui
src/qt/veil/forms/settingsfaq10.ui
src/qt/veil/settings/settingsfaq.cpp
src/qt/veil/settings/settingsfaq08.cpp
src/qt/veil/settings/settingsfaq09.cpp
src/qt/veil/settings/settingsfaq10.cpp

closes https://github.com/Veil-Project/veil/issues/96 (ordering issue)
- old 'extreme privacy' page is removed since it had no question/radio-button associated.
- 'contact veil support' page (faq11) commented out since there's no content for it yet.

[GUI] match FAQ items with their content

---

src/qt/coincontroldialog.cpp
src/qt/sendcoinsdialog.cpp

The commented code in coincontroldialog.cpp works. It seems the reason it was commented out was because it causes a segfault when the coins are selected and "OK" is clicked. This came from a line in sendcoinsdialog.cpp that would update the labels after the window was closed. The line is now commented and selected coins show the stats. The segfault no longer occurs.

Fix coin selection prompt to show stats.

---

src/hash.h
src/libzerocoin/CoinSpend.h

Use std::unique_ptr to avoid warning for variable length array
Change order of member variable initialization in CoinSpend

Fix a couple of C++ compiler warnings

---

src/primitives/block.h

seems to prevent segfault with local stratum; evidenced by waves of nodes reannouncing after connectblock errors..

dont branch based on potentially uninit var

---

src/init.cpp
src/miner.cpp
src/wallet/init.cpp

- Added ability to start the wallet PoW CPU mining thread with -gen=numberofthreads
- Added PoW mining sleeps if InitialBlockDownload was found to be true
- Add override flag -genoverride that overrides the InitialBlockDownload check in the miner ( This is hidden and wont be shown in the help screen, but could be useful for developers)
To start the miner with 4 threads miner, you would do the following
Daemon - **./veild -gen=4** 
Qt - **./qt/veil-qt -gen=4**
veil.conf - **gen=4**

Add ability to start mining using cmd flag -gen

---

src/interfaces/wallet.cpp
src/interfaces/wallet.h
src/miner.cpp
src/qt/veil/settings/settingsminting.cpp
src/validation.cpp
src/veil/ringct/anon.cpp
src/veil/ringct/anonwallet.cpp
src/veil/ringct/anonwallet.h
src/veil/ringct/outputrecord.cpp
src/veil/ringct/outputrecord.h
src/veil/ringct/rpcanonwallet.cpp
src/veil/ringct/transactionrecord.h
src/veil/zerocoin/ztracker.cpp
src/wallet/rpcwallet.cpp
src/wallet/rpczerocoin.cpp
src/wallet/wallet.cpp
src/wallet/wallet.h

**Fixed:**
- Sending zerocoin/RingCT/CT from the GUI send dialog
- Zerocoin mint from CT and RingCT.
- Deadlock when minting zerocoins.
- Zerocoinspend tx meta data not correctly tied to tx because of the txhash changes after signature.
- Basecoin balances
- CT Balances
- Properly select CT/RingCT output type for change situations.
- Allow Basecoin checkbox and rpc flag now used as "Use Basecoins" which will specifically only use basecoins for that tx.
- Automatically archive bad mints if possible.
- Mark anon output as spent if during spending the key image is found on the blockchain DB.
- Mark CT inputs as spent when spending them.
- Don't try to add loose coinstake transactions to mempool.
**Problems not solved:**
- Still seeing a blockchain corruption periodically when restarting, …

Fix a wide range of transaction issues.

---

src/rpc/blockchain.cpp
src/rpc/client.cpp
src/txmempool.cpp
src/txmempool.h
src/validation.cpp
src/veil/zerocoin/zchain.cpp
src/veil/zerocoin/zchain.h
src/wallet/rpcwallet.cpp
src/wallet/rpczerocoin.cpp

RPC:
- Add `findserial` from PIVX. Returns txid associated with zerocoin serial.
- Add clear mempool option to `abandontransaction`
- Add `rescanzerocoinwallet` which combines `resetzerocoinmint` `resetzerocoinspend` `reconsiderzerocoins`
Mempool:
- Add better filtering of zerocoin serials and pubcoins that currently reside in the mempool.

Better tracking of mempool. Add some RPC calls.

---

src/core_write.cpp
src/interfaces/wallet.cpp
src/interfaces/wallet.h
src/miner.cpp
src/net_processing.cpp
src/policy/policy.cpp
src/qt/transactionrecord.cpp
src/qt/transactionrecord.h
src/qt/transactiontablemodel.cpp
src/txmempool.cpp
src/txmempool.h
src/validation.cpp
src/veil/ringct/anonwallet.cpp
src/veil/ringct/anonwallet.h
src/veil/ringct/anonwalletdb.cpp
src/veil/ringct/anonwalletdb.h
src/veil/ringct/rpcanonwallet.cpp
src/veil/ringct/transactionrecord.h
src/veil/zerocoin/mintmeta.h
src/veil/zerocoin/zchain.cpp
src/veil/zerocoin/zchain.h
src/veil/zerocoin/ztracker.cpp
src/veil/zerocoin/ztracker.h
src/wallet/crypter.cpp
src/wallet/rpczerocoin.cpp
src/wallet/wallet.cpp
src/wallet/wallet.h

- Additional filtering of transactions in mempool
- Check if there are conflicts with any transactions in the mempool that contain zerocoinspend serials or zerocoinmint pubcoins
- Check pubcoins and serials to see if they have already been used on the blockchain (fixes #232)
- Additional checks performed in block creation (same checks as were added to mempool)
- Ensure block time is not out of bounds (fixes #231)
- Remove any conflicting zerocoin spends/mint from mempool when a new block is added.
- Replace certain areas using `IsInitialBlockDownload()` with `HeadersAndBlocksSynced()`.
- Consider certain zerocoinspend as not standard
- Add addresses to transaction records for stealth addresses.
- Better recognition of transaction types for GUI tx records.
- Fix errors that were deleting …

Wallet scans. Tx Records. Encryption. Mempool filtering.

---

src/miner.cpp

Fix bad scope in miner check causing failure to create blocks.

---

src/core_write.cpp

Decoding raw transactions, mark the output of coinbase TX as "coinbase" to distinguish it from coinstake output.

Add a flag to coinbase TX output in OutputToJSON

---

src/wallet/wallet.cpp
src/wallet/wallet.h

Fixes the issue where sending CT or ringCT to basecoin doesn't show up under balances.
(fixes #309)

Fix CT and ringCT to basecoin balance issue

---

src/chain.cpp
src/chain.h
src/chainparams.cpp
src/chainparams.h
src/consensus/params.h
src/consensus/validation.h
src/miner.cpp
src/net_processing.cpp
src/rpc/blockchain.cpp
src/validation.cpp
src/validation.h
src/veil/proofofstake/kernel.cpp
src/veil/proofofstake/kernel.h
src/veil/ringct/anonwallet.cpp
src/veil/ringct/anonwallet.h
src/veil/ringct/outputrecord.cpp
src/veil/ringct/rpcanonwallet.cpp
src/veil/zerocoin/accumulators.cpp
src/versionbits.cpp
src/wallet/init.cpp
src/wallet/rpcwallet.cpp
src/wallet/rpczerocoin.cpp
src/wallet/wallet.cpp
src/wallet/wallet.h

**VIP-1 Soft Fork:**
---
**VIP link:** [VIP-0001](https://github.com/Veil-Project/VIP/blob/master/vip-0001.mediawiki) 
**Implementation Detail:** The default wallet will now use no stake weight reduction for any denomination of zerocoin, since enforcement was not properly added to the codebase. Once the enforcement threshold is met, stake weight will automatically revert back to reduced weight for larger denomination.
**Soft Fork Detail:** 
- Bit signal on version bit 2
- Each voting period 1440 blocks (1 day)
- Activation threshold 75% 1080 blocks
**Spam and DoS Prevention**
---
**Background Information:** A recent security analysis and associated research paper have identified some areas of concern for DoS attacks against many Proof of Stake based cryptocurrencies …

Prevent headers and blocks spamming. Add VIP-1 soft fork.

---

CMakeLists.txt
src/Makefile.test.include
src/init.cpp
src/libzerocoin/SerialNumberSoK_small.cpp
src/libzerocoin/SerialNumberSoK_small.h
src/logging.cpp
src/logging.h
src/net_processing.cpp
src/net_processing.h
src/test/zerocoin_implementation_tests.cpp
src/test/zerocoin_zkp_tests.cpp
src/validation.cpp
src/validation.h
src/veil/zerocoin/zchain.cpp
src/veil/zerocoin/zchain.h
src/veil/zerocoin/ztracker.cpp
src/wallet/rpcwallet.cpp

- Split block staging into two threads, one for adding blocks to the chain, the other for verifying proofs.
- Don't ask for block announcements more than three times.
- Don't process a block if it is already part of the main chain.
- Threaded batch verify. Default of 2 threads, able to be changed using `-threadbatchverify=`
- Add unit tests for batch verification of proofs.

Multi Threading of Block Staging and Proof Verifying

---

src/wallet/wallet.cpp
src/wallet/wallet.h

The wallet was scanned for zerocoin spend inputs both in `SpendZerocoin` and in `CreateZerocoinSpendTransaction` (called by the former) resulting in extra selected mints when the vector `vMintsSelected` was already filled with user-provided mint list (e.g. when accessing via the rpc method `spendzerocoinmints`).
The vector of mints is now filled only in a new method `CWallet::CollectMintsForSpend` and assumed always already populated inside `CreateZerocoinSpendTransaction`.
This should fix issue https://github.com/Veil-Project/veil/issues/380
____________
In order to resolve a segfault when no destination address is provided to `CreateZerocoinSpendTransaction`, the method now returns error in that case (06ec8cf).

[Wallet] Refactor zerocoin mints collection before spending

---

src/veil/ringct/anonwallet.cpp
src/veil/ringct/anonwallet.h

This fixes issues with not being able to spend CT and RingCT inputs under certain circumstances.

[Wallet] Use a temp keystore for signing stealth inputs.

---

src/interfaces/wallet.cpp
src/interfaces/wallet.h
src/qt/sendcoinsdialog.cpp
src/qt/walletmodel.cpp
src/qt/walletmodel.h
src/veil/ringct/rpcanonwallet.cpp
src/wallet/feebumper.cpp
src/wallet/rpcwallet.cpp
src/wallet/test/wallet_tests.cpp
src/wallet/wallet.cpp
src/wallet/wallet.h

This should resolve #272.
I split the ZerocoinSpend into preparation and commit steps. We now prepare the ZerocoinSpend when we first click "Send" in the GUI (just as we were doing with other types of transactions), and we won't commit the ZerocoinSpend until the "Send" button in the confirmation popup is clicked. Previously, these two steps were not separated and were both performed as soon as the first "Send" button was pressed (before the user confirmed sending the zerocoin).

[Wallet][Qt] Fix premature Zerocoin spending in GUI

---

src/veil/zerocoin/denomination_functions.cpp
src/veil/zerocoin/denomination_functions.h
src/wallet/wallet.cpp

Order mints by descending confirmations before zcspend input collection.
Closes https://github.com/Veil-Project/veil/issues/402

[Wallet] Select oldest zerocoinmints first when spending zerocoins

---

src/rpc/blockchain.cpp
src/rpc/client.cpp
src/veil-cli.cpp

This introduces a new RPC method, `getzerocoinsupply`,  to get the zerocoin supply per denomination at given height and the percent relative to the total supply.
It can be used either as a standalone call or as part of `getblockchaininfo`/`-getinfo`.
Examples:
```
:~$ veil-cli getzerocoinsupply 2130
[
{
"denom": "10",
"amount": 4224000000000,
"percent": 39.67670183985004
},
{
"denom": "100",
"amount": 450000000000,
"percent": 4.226921360779478
},
{
"denom": "1000",
"amount": 200000000000,
"percent": 1.87863171590199
},
{
"denom": "10000",
"amount": 0,
"percent": 0
},
{
"denom": "total",
"amount": 4874000000000,
"percent": 45.78225491653151
}
]
```
```
:~$ veil-cli -getinfo
"version": 99,
"protocolversion": 70022,
"walletversion": 169900,
"balance": 0.00000000,
"blocks": 71077, …
```

[RPC] introduce new 'getzerocoinsupply' method

---

src/validation.cpp
src/veil/budget.cpp
src/veil/budget.h

This fixes two problems with contextual checks on superblock.
- bad-coinbase-vpout would be triggered for valid PoS superblocks  (mainnet and testnet) after the  first one.
- CheckBudgetTransaction does not reflect the changes introduced with https://github.com/Veil-Project/veil/pull/299 (only testnet)

[Consensus] fix superblock consensus bugs

---

src/rpc/blockchain.cpp

simple check preventing `getzerocoinsupply`, `getblockchaininfo`, `-getinfo` from returning "error: couldn't parse reply from server" when pindex is null or money supply is zero (e.g. when trying to sync from scratch with no peers connected yet)

[RPC] getzerocoinsupply - add checks for null supply

---

src/init.cpp

Veil Copyright notice was appearing as duplicated, one notice before Bitcoin, and one notice after Particl. Veil Copyright year has also been fixed (2009 --> 2018).
Visual example of the (**current**) wallet's Information menu:
---
Visual example of this PR's **edited** Information menu:

[UI] Fixed Copyright notices in LicenseInfo()

---

src/consensus/tx_verify.cpp
src/init.cpp
src/miner.cpp
src/net_processing.cpp
src/validation.cpp
src/validation.h
src/veil/ringct/anonwallet.cpp
src/veil/ringct/anonwallet.h

- Fix some situations where wallet fails to get CT blinds when spending RingCT.
- Speed up reindexing by skipping computation.
- Track pubcoins that have been validated and do not revalidate them.
- Fix issues with stuck headers if chain too old.

[Wallet][Network][Consensus] Miscellaneous bug fixes.

---

src/qt/veil/forms/unlockpassworddialog.ui

- After typing your password to unlock the wallet. You had to use the mouse to click the unlock button. This change enables the use of the return/enter key to trigger the unlock button.

[QT] Enable return/enter on unlock screen password submission

---

src/qt/coincontroldialog.cpp
src/qt/coincontroldialog.h
src/qt/forms/coincontroldialog.ui
src/qt/forms/sendcoinsdialog.ui
src/qt/forms/sendcoinsentry.ui
src/qt/sendcoinsdialog.cpp
src/qt/sendcoinsdialog.h
src/qt/sendcoinsentry.cpp

- Added labels to the send dialong if coin control has selected coins
- Added coin type selector to coin control for easier access to certain coins
New Labels
New dropdown menu 
Dropdown menu items
**GUI might look off because I am taking these screen shots on linux running kubutu**
**This needs to be tested on all platforms**
#430

Add coin control updates to veil send dialog

---

src/txdb.cpp

fixes #422
It is also possible that #405 is related, but not positive.
For some reason multiple indexes are being saved to disk for the same block. The second index will overwrite the first index on first load. The second index has `nTx` set to `0`, as well as all relevant block file locations. The second index causes all subsequent indexes to have `nChainTx` set to `0`, causing them not to be able to be considered block candidates. Also notable is that the second index has the wrong database key which is supposed to be the block hash but is not.
This change simply ignores the second block index on first load. It is still yet to be determined what causes the duplicate index.

Do not load corrupted duplicate block indexes.

---

.travis.yml
.travis/README.md
.travis/lint_04_install.sh
.travis/lint_05_before_script.sh
.travis/lint_06_script.sh
.travis/test_03_before_install.sh
.travis/test_04_install.sh
.travis/test_05_before_script.sh
.travis/test_06_script_a.sh
.travis/test_06_script_b.sh
test/lint/lint-filenames.sh

This overhauls the TravisCI descriptors with upstream changes and optimizations. Some notes:
* Running the Unit Tests is currently disabled due to pre-existing errors
* Running the Regtest Functional test suite is disabled due to it being incomplete with the veil code/network
* Linting the `src/secp256k1` and `src/univalue` subtrees are disabled due to divergences from upstream
* Linting the RPC mappings is disabled due to pre-existing failures
* Running the `lint-all.sh` script is disabled due to pre-existing failures
* Build targets that make use of `--disable-wallet` are disabled due to pre-existing compile-time errors with that configuration
* The macOS build target is being compiled without the `--enable-werror` configure flag due to pre-existing thread safety errors
These things can …

[Build] Update TravisCI Descriptors

---

src/interfaces/wallet.cpp
src/interfaces/wallet.h
src/primitives/transaction.h
src/qt/coincontroldialog.cpp
src/qt/coincontroldialog.h
src/qt/forms/coincontroldialog.ui
src/qt/forms/sendcoinsdialog.ui
src/qt/sendcoinsdialog.cpp
src/qt/walletmodel.cpp
src/wallet/coincontrol.cpp
src/wallet/coincontrol.h
src/wallet/wallet.cpp
src/wallet/wallet.h

- Add ability to select zerocoin denomination from coin control when spending
- Coin control will show zerocoin precomputation percentage if it is enabled and running 
**Precomputation isn't running**
**Precomputation is running**
Closes #431

Add zerocoin to coincontrol

---

src/miner.cpp

Headers are not fully valid yet, so don't trust the data on them for the stake miner's control flow.

Don't use header time to pause stake miner.

---

src/veil/ringct/anonwallet.cpp

If an output record has an empty scriptpukkey, then look it up manually instead of failing.
fixes #486

[Wallet]Fix empty scriptpubkey causing issues creating CT transactions.

---

src/rpc/client.cpp
src/veil/ringct/anonwallet.cpp
src/veil/ringct/anonwallet.h
src/veil/ringct/anonwalletdb.cpp
src/veil/ringct/anonwalletdb.h
src/veil/ringct/stealth.cpp
src/veil/zerocoin/zchain.cpp
src/veil/zerocoin/zwallet.cpp
src/veil/zerocoin/zwallet.h
src/wallet/rpcwallet.cpp
src/wallet/rpczerocoin.cpp
src/wallet/wallet.cpp
src/wallet/wallet.h

`recoveraddresses` rpc can be used after importing a seed to the wallet. By default it will create 100 stealth addresses, 100 basecoin addresses, and 100 deterministic zerocoins (can be changed using `count`). It will then scan the full blockchain for any activity that is owned by the wallet. Since stealth addresses add computational overhead to block syncing, the rpc call will remove any of the unused stealth addresses. 
The process does keep a small buffer of up to 20 (`unused_buffer`) unused stealth addresses to accommodate the possibility that generated addresses were given out as a receiving addresses, but not used yet.
Users can also specify a block to start the search from in order to speed up the process (`scan_from_block`).
closes #453

[Wallet][RPC] Add recoveraddresses rpc to regenerate keys and zerocoins after a seed import.

---

src/qt/transactionrecord.cpp

Remove the denomination amount that won the stake. The amount the wallet gained is value of the stake.
closes #429

[Wallet] Transaction Detail - Remove the denomination amount that won the stake

---

src/veil/zerocoin/zwallet.cpp

- Statically compile windows builds on linux was failing. This change fixes the windows build problem

[Build] Fix windows build with boost thread

---

src/consensus/tx_verify.cpp
src/veil/zerocoin/lrucache.cpp
src/veil/zerocoin/lrucache.h
src/veil/zerocoin/precompute.h
src/veil/zerocoin/witness.cpp
src/veil/zerocoin/witness.h

- Rename the precompute lru cache class
- Create new lru cache template class that is bare bones and easy to use
- Replace set that was causing segfault to occur when checking zerocoinmint
Closes #531

New lru cache

---

src/veil/ringct/anonwallet.cpp
src/veil/zerocoin/ztracker.cpp
src/wallet/wallet.cpp
src/wallet/wallet.h

- Automint uses the highest balance first
- RingCT is now added to automint
- CT is now added to automint
- Fix automint full balance
- Automint will now try and mint up to 9 zerocoin at a time
If balance is 1200 CT, and 100 denom is selected to automint. 
9 100 mint denoms will be created. 
2c8749803201135c61d9a76db0bdaf80ba4bf7dc Closes #438 Closes #434 
049ea5b8988e177429d0ccd039715f398ce4de2c Closes #415

Add ringct and ct to automint

---

src/veil/ringct/anonwallet.cpp

- Fixes issue 471 by making the balance become available after the 11 confirmation block, not on the 11 confirmation
Closes #471

Fix mintable ringct and ct balances to show correcly

---

CMakeLists.txt
src/Makefile.am
src/Makefile.test.include
src/chainparams.cpp
src/chainparams.h
src/consensus/params.h
src/init.cpp
src/libzerocoin/CoinSpend.cpp
src/libzerocoin/CoinSpend.h
src/libzerocoin/PubcoinSignature.cpp
src/libzerocoin/PubcoinSignature.h
src/net_processing.cpp
src/rpc/blockchain.cpp
src/test/zerocoin_implementation_tests.cpp
src/test/zerocoin_pubcoinsig_tests.cpp
src/validation.cpp
src/validation.h
src/version.h
src/versionbits.cpp
src/wallet/rpcwallet.cpp
src/wallet/wallet.cpp

Due to disclosures made by [ZCoin](https://zcoin.io/further-disclosure-on-zerocoin-vulnerability/), and lots of analysis done with other teams such as ZCoin and PIVX, Veil will be placing its zerocoin protocol into a functional but **not anonymous** state. The transition will occur rapidly and be done using bit signalling in the block header.
Every zerocoin spend/stake will have no longer have any privacy associated with it and should be considered as transparent as a basecoin transaction. More details will follow soon that will provide a complete detailed breakdown and analysis of why these changes are being made.
- This puts zerocoin into what we call *limp mode*. 
- The privacy of both **CT and RingCT are not impacted by this.**
Every zerocoin mint has an identifier that gets added to …

[Consensus][Wallet]Put Zerocoin into "Limp Mode"

---

src/Makefile.test.include
src/libzerocoin/bignum.h
src/test/zerocoin_bignum_tests.cpp
src/test/zerocoin_denomination_tests.cpp
src/test/zerocoin_implementation_tests.cpp

This fixes an issue where the GMP bignum PRNGs could output numbers slightly bigger than the max size set.

[Zerocoin] GMP BigNum: Fix limits for random number generators

---

src/qt/forms/optionsdialog.ui
src/qt/optionsdialog.cpp
src/qt/res/css/main.css
src/qt/veil.cpp

Set the style sheet at the application level. This is a workaround provided by the Qt developers to stop cut off text in tooltips.
QT-BUG: https://bugreports.qt.io/browse/QTBUG-64550
QT-BUG: https://bugreports.qt.io/browse/QTBUG-41313
All tooltips will have a light blue background.
fixes #63 
fixes #54

[Qt] Fixes cut off tool tip text across the application

---

src/qt/bitcoingui.cpp
src/qt/veil/forms/veilstatusbar.ui
src/qt/veil/veilstatusbar.cpp
src/qt/veil/veilstatusbar.h

Add a Block height indicator `syncIndicatorBtn` to `veilStatusBar` to display current block height.
This should help with the issues #462 & #221 
Receiving Address
```
```
Thanks,
M

[GUI] Sync progress ui additions

---

src/qt/sendcoinsentry.cpp

- Allow for 8 decimals instead of the current 7
- Remove commas from being added to the amount
Closes #488

[Qt] Update pay amount text box

---

src/qt/transactionrecord.cpp
src/qt/transactionrecord.h
src/qt/veil/transactiondetaildialog.cpp

Adds Transaction Size to Transaction Detail Dialog.
I chose to display the size in Bytes, for the sake clarity.
Closes: #523 
Bounty payment address:
sv1qqp0j5cm6vrrkvkajpnq39gczt09eclw5z8h2zrmvrwndw7ppqaa28spqfqmkpana500t0jmjnhcjekg0rgt9jfll3w03m46p7ard9lqrpxduqqqe9a2qv

[Wallet] Add Transaction Size to Transaction Detail Dialog

---

src/chainparams.cpp
src/wallet/rpczerocoin.cpp

- Added new testnet checkpoint for quicker signature verification
- Added support for stealth address to the **spendzerocoinmints** rpc call
- Added support for bech32 addresses to the **spendzerocoinmints** rpc call
Example use of the rpc call to a stealth address
Example use of the rpc call to a bech32 address
Closes #459

[RPC] Allow all address types in spendzerocoinmints

---

src/chainparams.cpp
src/validation.cpp

Remove bit 2 warning.

---

src/qt/forms/overviewpage.ui
src/qt/overviewpage.cpp
src/qt/overviewpage.h

Adding filtering functionality to the transactions list.
Closes #540 
Transactions can now be filtered using the Taxonomies;
- Sent
- Received
- Mint
- Mined
- Stake
- Basecoin
- RingCT
- CT
- ZeroCoin
- All
Bounty Address
```
```

[GUI] Add transaction list filtering

---

src/qt/veil/forms/veilstatusbar.ui
src/qt/veil/veilstatusbar.cpp

A single click now triggers the initial unlock of the wallet by clicking `btnLock`
- Added focus policy
- Removed unnecessary signal blocks.
closes #553 
Bounty Address
```
```

[GUI] Lock button focus & signal blocking fix.

---

src/qt/res/css/main.css
src/qt/veil/forms/veilstatusbar.ui

Closes #503 
- Indicator of `checkStaking` & `checkPrecompute` have been extended to cover toggle switch.
- `checkStaking` is now styled within `QtCreator`
- Updated `main.css` to include styling for `checkStaking` & `checkPrecompute` 
Bounty Address
```
```

[GUI] Extending clickable area of Staking & Precompute toggle switch.

---

src/veil/ringct/rpcanonwallet.cpp

Help block now matches standard format of other help blocks.
Closes #428

[RPC] Correcting help format of `rescanringctwallet`

---

src/qt/optionsdialog.cpp

The frame that contains the checkboxes has it background color set to transparent. The checkboxes were picking up this cascading style and making the checkbox transparent. background: none will revert the transparent background.
fixed #546 
sv1qqpj0zn0pyd2gp7w5vs93ja2rq0s6yrwvmtcvvd6lg5awdpuggsh32cpq2seytp7tg6mlqvzn2zjl9ug63gsga0q5kgzh5sjmg0uz32r2krh6qqq4tpdvx

[GUI] Prefences tab - revert background to allow native OS styling

---

src/qt/sendcoinsentry.cpp
src/wallet/rpczerocoin.cpp

Adding Address validation to ensure `addressTo` is both provided and a valid stealth address.
#495

[RPC] SpendZeroCoin Address Validation

---

src/core_io.h
src/core_write.cpp
src/rest.cpp
src/rpc/blockchain.cpp
src/rpc/rawtransaction.cpp
src/veil-tx.cpp
src/veil/ringct/anon.cpp
src/veil/ringct/anon.h
src/veil/ringct/anonwallet.cpp
src/veil/ringct/anonwallet.h
src/veil/ringct/rpcanonwallet.cpp
src/wallet/rpcwallet.cpp

In some situations spending RingCt would fail because of missing blinds.
`gettransaction` and `getrawtransaction` will now print the list of RingCt inputs used in a RingCt spend.

[Wallet][RPC]Fix missing RingCt Blinds. Add RingCt inputs print to getrawtransaction.

---

src/qt/askpassphrasedialog.cpp
src/qt/veil/settings/settingsminting.cpp

Make input boxes work on Return/Enter event.
This changes unlock wallet, encrypt, change password and mint settings screens.
Fixes #502

Add ReturnPressed event to labels

---

depends/packages/qt.mk
src/qt/forms/sendcoinsdialog.ui
src/qt/overviewpage.cpp
src/qt/sendcoinsdialog.cpp
src/qt/sendcoinsdialog.h
src/qt/transactionfilterproxy.h
src/qt/veil/addresseswidget.cpp
src/qt/walletmodel.cpp
src/veil/zerocoin/accumulators.cpp
src/wallet/wallet.cpp

- Run send coins on a different thread and emit a signal when it is done.
- Make `cs_wallet` lock more fine grain on `SpendZerocoin()` so that it does halt all other items that use `cs_wallet`. This allows the UI to continue to be used while a transaction is being created.
- Add a status label that displays (and animates) the current state of transaction creation.
- Disable spend button if a transaction is being generated.
- Use a small security level for zerocoinspends since zerocoin is not anon right now anyways.
- Refactor some bad GUI code that pointlessly calls wallet methods that wait on `cs_wallet` lock.
Dev Note: This adds QtConcurrent to the depends.
Use Example:
Tabs Being Switch While Tx Is Being Generated:
Button disabled when send is pressed:

[Qt][Wallet]Make send dialog more asynchronous.

---

src/qt/walletmodel.cpp
src/veil/ringct/anonwallet.cpp
src/wallet/rpczerocoin.cpp
src/wallet/wallet.cpp

- Sending less than 10 veil by spending a zerocoin in your wallet would make the transaction fail, without any error message being sent to the user. 
- This fixes that issue by allowing the zerocoin spend to complete
- This also adds some error logs if the spend fails to happen again, so it can be troubleshooted
Closes #555 
Closes #584 
Test Preconditions:
1. Wallet must contain at least 1 zerocoin ( I had some 10 denoms in my wallet) , and that zerocoin must be spendable
Test steps:
1. Try to send a value less than 10 veil to an address. 
2. Wait for the transaction to be confirmed
3. Try to spend the change that was made from the above transaction to another address ( you can use coincointrol to selected the specific outpoint to use when making this spend) 
Edit: Adding more QA …

[Wallet] Remove check for amount less than 10

---

src/wallet/rpczerocoin.cpp

This PR fixes #610, corrects the help message on RPC "rescanzerocoinwallet" as it was previously displaying the help message for "resetmintzerocoin".

[RPC] Fix rescanzerocoinwallet help message

---

src/chainparams.cpp
src/init.cpp
src/rpc/client.cpp
src/wallet/init.cpp
src/wallet/rpczerocoin.cpp
src/wallet/wallet.cpp
src/wallet/wallet.h
src/wallet/walletdb.cpp
src/wallet/walletdb.h

- Fixes regtest params to work with stealth addresses
- Added rpc call **startautospend** with three optional paramters (address, count, type)
1. Address - The stealth address to auto spend to (if not given one will be generated)
2. Number of spends: the number of spends to make per cycle ( 1 - 3)
3. The denomination to spend ( 10, 100, 1000, 10000)
- Added rpc call **stopautospend** which stops the autospend thread
- Added rpc call **getautospendaddress** which shows the current address set to auto spend to
- Added new arugments
1. **-autospend** enables the autospend thread
2.  **-autospendcount=number** the number of spends to make per cycle (1-3)
3. **-autospenddenom=number** the denomination to spend ( 10, 100, 1000, 10000)
4. **-autospendaddress=string** the destination address for …

[Wallet] Add ability to autospend zerocoin denominations

---

src/qt/veil/forms/veilstatusbar.ui

The status bar was missing a horizontal spacer on the left side of the sync status button
fixed #602 
sv1qqpj0zn0pyd2gp7w5vs93ja2rq0s6yrwvmtcvvd6lg5awdpuggsh32cpq2seytp7tg6mlqvzn2zjl9ug63gsga0q5kgzh5sjmg0uz32r2krh6qqq4tpdvx
Before Fix:
After Fix:

[GUI] Status bar – Horizontally center the sync status button

---

src/wallet/rpczerocoin.cpp

Add destination address validition to spendzerocoin
Closes: #495 
payment address:
sv1qqp0j5cm6vrrkvkajpnq39gczt09eclw5z8h2zrmvrwndw7ppqaa28spqfqmkpana500t0jmjnhcjekg0rgt9jfll3w03m46p7ard9lqrpxduqqqe9a2qv

[RPC] Require a valid destination address in spendzerocoin

---

src/qt/veil/balance.cpp
src/qt/veil/receivewidget.cpp

Removes an unnecessary wallet lock check, which could cause a segmentation fault under certain conditions. If no address labeled "stealth" was present (due to renaming) in an encrypted (password locked) wallet at startup, the client would segfault.
This resolves #452

Remove obsolote wallet lock check

---

src/qt/coincontroldialog.cpp

When spending zerocoin the UI was displaying a fee amount that was not included in the actual transaction. 
fixes #596 
sv1qqpj0zn0pyd2gp7w5vs93ja2rq0s6yrwvmtcvvd6lg5awdpuggsh32cpq2seytp7tg6mlqvzn2zjl9ug63gsga0q5kgzh5sjmg0uz32r2krh6qqq4tpdvx

[GUI][Wallet] Remove unnecessary fee amount from Zerocoin spend

---

src/qt/forms/optionsdialog.ui

The qproperty-alignment property is not a valid css or qt property. 
closes #533
sv1qqpj0zn0pyd2gp7w5vs93ja2rq0s6yrwvmtcvvd6lg5awdpuggsh32cpq2seytp7tg6mlqvzn2zjl9ug63gsga0q5kgzh5sjmg0uz32r2krh6qqq4tpdvx

[GUI] Remove invalid combobox styling

---

src/chainparams.cpp

- Regtest doesn't function correctly because of an issue with some issue chain params. With the chain params added back, we are able to use regtest again.

[Wallet] Fix regtest chainparams

---

src/qt/walletview.cpp

sets 'wallet-..-..' default filename in backup dialog fix #247  
bv1qxmzawm3a085u2vlq9pn27zphr7nteqdeeal6y9

'wallet-..-..' default filename 

---

src/veil/ringct/anonwallet.cpp
src/veil/ringct/anonwallet.h
src/veil/ringct/rpcanonwallet.cpp
src/wallet/wallet.cpp

Currently the wallet generates a new stealth address everytime it needs to issue change in a transaction that has CT or RingCT outputs. Creating a new stealth address each time is bulky and increases the amount of scanning that needs to happen when checking the blockchain for transactions that belong to the wallet.
Since a new stealth destination is derived from a stealth address each time it is used, it provides the same utility if the wallet uses a dedicated change address.
This adds a dedicated change address that is in a specific location on the seed's key path.
This also adds `getstealthchangeaddress` RPC which will print out the default change address.

[Wallet] Use one default stealth change address for CT/RingCT transactions.

---

SECURITY.md

There is a new development within the open source community that github supports. By adding a file named **"Security.md"**, projects document their security reporting process in a new _"Security"_ Tab.
Related information
https://github.com/github/opensource.guide/issues/981
This pull request adds a responsible disclosure statement and procedure to the project repo in a new file "SECURITY.md". This information will than be displayed at https://github.com/Veil-Project/veil/security/policy and can be easily referenced where needed.
This is my proposal how a reasonable _"Security.md"_ for Veil should look like.

Add SECURITY.md to the project repo to outline the security reporting process

---

src/qt/addressbookpage.cpp
src/qt/addressbookpage.h
src/qt/sendcoinsentry.cpp
src/qt/sendcoinsentry.h
src/qt/veil/addressesmenu.cpp
src/qt/veil/addressesmenu.h
src/qt/veil/addresseswidget.cpp
src/qt/veil/addresseswidget.h
src/qt/veil/addressreceive.cpp
src/qt/veil/addressreceive.h
src/qt/veil/balance.cpp
src/qt/veil/balance.h
src/qt/veil/receivewidget.cpp
src/qt/veil/receivewidget.h
src/qt/veil/settings/settingswidget.cpp
src/qt/veil/settings/settingswidget.h

Clicking on an address in the Address Book page to pull up the Copy|Edit menu generates "No matching signal" errors in debug.log the first time you use the menu.
The Qt MetaObject `connectSlotsByName` searches for `connect()` code with slot objects that conform to the format `on_<object-name>_<signal-name>`.  Since the signals for that pulldown (`on_btnCopyAddress_clicked()`, `on_btnEditAddress_clicked()` and `on_btnDeleteAddress_clicked()`) conformed to that format; connectSlotsByName picked them up when they shouldn't have been.
Rename these slots in the format `on<Object-name>Clicked` to avoid moc from picking them up inadvertently.
Several other instances of the same issue were found and corrected in this PR.
_Also included in this PR:_ …

[GUI][QT] Fix "no such slot" and "no matching signal" log errors

---

src/qt/bitcoingui.cpp
src/qt/res/css/main.css

fixes #577 
This gives the progress bar that is called in the small progress dialog its own styling for text alignment.

[Qt] Align text in the center of the progress bar.

---

src/qt/veil/receivewidget.cpp
src/qt/veil/receivewidget.h

Clicking the "Generate Address" circle arrow icon in the bottom left of the Receive screen shows a pop up for "address generated" but doesn't generate a new address.
`ReceiveWidget::generateNewAddress()` has multiple uses.  It's called by `setWalletModel()`, `refreshWalletStatus()`, and when you click on the "Generate Address" icon.  The first use is to generate a new address if you don't already have one.  The second is to get the label of your initial address.  These two uses required the original `generateNewAddress()` to need a change; so that it wouldn't create a new address every time you started the wallet.
That fix introduced the issue in question.  Because the fix was made by not generating a new address if an address already exists.  Since the nature of having the wallet up and …

[QT] Fix address creation on Receive tab

---

src/rpc/blockchain.cpp

`getblockstats` returns 'tx index seems corrupt' on many blocks.
`getblockstats` did not recognize when transaction inputs were not "normal";  This occurs on zerocoin spends, as well as ringCT transactions.  Furthermore, it got confused when there was a PoS block, and most PoS blocks caused the error.
Skip transactions that are coin stake transactions, or ring ct transactions.  For zerocoin transactions, get the amount of zerocoin spent.
#440 
`sv1qqpj9l2f883k7ucs88xdzrcuus8wr6jzrnk85quv3p2u90zwyy6d5tqpq0fl2ksmvlsf5hfddf8ezqnph5q6zf05cmac28g6ytafdzp8aufsuqqqwk9ep3`
```
$ veil-cli getblockstats 307836
error code: -32603
error message:
Unexpected internal error (tx index seems corrupt)
$ veil-cli getblockstats 307867
error code: -32603
error message:
Unexpected internal error (tx index …
```

[RPC] Fix getblockstats to handle zerocoin spends, RingCT and PoS blocks

---

src/chainparams.cpp
src/chainparams.h
src/miner.cpp
src/miner.h
src/policy/policy.cpp
src/validation.cpp
src/veil/proofofstake/kernel.cpp
src/veil/proofofstake/stakeinput.cpp
src/wallet/walletdb.cpp
src/wallet/walletdb.h

- Fix a few segfaults, mostly related to PoS.
- Lock the walletdb anytime it reads or modifies. There were a few cases of multithreaded access that caused a double free to be thrown.
- Consider any tx with more than 15 zerocoin mints as nonstandard.
- Don't include more than 70 zerocoinmints per block. This is still a very large amount of mints, it may be able to be reduced further in the future, or have a user configurable setting.
- Add some fail flags to the mining process. These do not do anything at the moment, but can help in the future if the miner should respond to certain failures in different ways.

Fix Stake Miner Segfaults. Add checks for too many zcmints in tx/block.

---

src/chainparams.cpp
src/veil/budget.cpp

When syncing with the latest code. Nodes were rejecting the block at height 1. This was because of a miss calculation on the amount. This PR fixes that, as well as adds another seed node for testnet

[Testnet] Update testnet params and fix amount

---

src/rpc/blockchain.cpp

While working through the RPC, I had noticed in the RPC command getzerocoincoinsupply, height is assumed to be required when it isn't. Small fix.

[RPC] getzerocoinsupply height not required

---

src/script/script.cpp
src/script/script.h

The scriptsig outputs from decoded RPC transactions show `OP_UNKNOWN` when displaying zerocoin transaction scripts.
The opcodes were defined in script.h (0xc1 & 0xc2 respectively) but a corresponding mapping for decoding scriptsig did not have the proper mappings.
```
"scriptSig": {
"asm": "OP_UNKNOWN 453 822223105 OP_ROLL 9 OP_NUMEQUALVERIFY 628cde83026d23fd5dcb02bc9da72c344679b3aff034739897e80446304402200d12f9f7ff0af09db1e6eeed30497222ffe535c6 OP_CODESEPARATOR OP_MAX OP_UNKNOWN OP_UNKNOWN OP_UNKNOWN 57b1c8b9f103022042d1304dc0309ff8d5295846f3a7a8099794c9a2bab9559eff OP_DEPTH OP_NOP8 OP_SWAP OP_UNKNOWN 658fe803000000000000327acd580a5604bc6244d70ee681cf506e2edf4b95 b51600fc1465d8469519b64165c8c618a0c4751891b0875c1afae3554fe43a25b5f5c3cc52e4171ae1215a59c373fb55c10dc6c1a39622d50261d59837e1e94 …
```

[script][RPC] Properly parse and display zerocoin opcodes

---

README.md

The build indicator badge on the project repo page doesn't report the correct TravisCI build status.
The badge URL is incorrect. 
Corrected the badge URL.
Added badges to display the last release version and date. 
Clicking the build badge will open https://travis-ci.com/Veil-Project/veil?branch=master
Clicking either release badge will open https://github.com/Veil-Project/veil/releases

[DOC] Corrected TravisCI badge, added release version and date badges

---

share/qt/Info.plist.in

Bitcoin Core's gui is pretty broken for a someone using macOS in "Dark Mode"; the biggest issue being lots of white text on a white background, leaving most inputs, the rpc console etc unusable.
This is likely something we'll have to wait for Qt to fix/support, so it's probably easiest to just disable for now, rather than provide a broken UI; 
Apple documentation on "Opting out of Dark Mode" is here.
>    If you need extra time to work on your app's Dark Mode support, you can temporarily opt out by including the NSRequiresAquaSystemAppearance key (with a value of true) in your app’s Info.plist file. Setting this key to true causes the system to ignore the user's preference and always apply a light appearance to your app.
Disable dark mode
1. Enable dark mode
2. Launch and use the wallet …

[GUI] Explicitly disable Dark Mode appearance on macOS

---

src/qt/veil/forms/transactiondetaildialog.ui
src/qt/veil/transactiondetaildialog.cpp

The view in explorer button on the transaction detail modal had tooltip style that didn't mastch the rest of the wallet. Depending on the OS the tooltip background would be black or transparent
The tooltip styling on the modal was overriding the QT style sheet.
Removed the custom tooltip style. Set the QT style sheet.
1. Navigate to the transaction listing.
2. Open a transaction 
3. Hover your mouse over the eye icon.
4. Verify the View in Explorer tooltip is displayed on a blue background with white text.
Before:
After:
fixed #685 
More information about the QT bug can be found here: #515

[QT] Correct "view in explorer" tooltip style

---

src/qt/overviewpage.cpp
src/qt/sendcoinsdialog.cpp
src/qt/veil/addresseswidget.cpp
src/qt/veil/addresseswidget.h
src/qt/veil/receivewidget.cpp
src/qt/veil/receivewidget.h
src/qt/veil/settings/settingswidget.cpp
src/qt/veil/settings/settingswidget.h

When restoring the wallet from a minimized state, or when completely covered by other windows; the receive, addresses, and settings tabs don't redraw.
This problem was introduced with PR #651 in response to Issue #541, where "no such slot" errors were generated when switching between windows.  The problem with the errors was a missing hideThisWidget() call.  That routine traditionally calls hide() to hide the widget.  However, when a widget is hidden on minimize, the showEvent() handler doesn't get called on restoration; so it didn't automatically redraw the widget.  One had to click away and back to get the showEvent() to trigger.
After some research, it seems that hiding the widget isn't really necessary; so instead of putting conditions to prevent the hide when minimizing (and then …

[Qt] Remove hide() on hideEvents

---

doc/gitian-building/README.md

The documentation related to the Gitian build process was updated to reference this repo: https://github.com/Veil-Project/docker-based-gitian-builder

[DOC] Updated gitian documentation to reference docker process

---

src/Makefile.qt.include
src/qt/locale/veil_en.ts
src/qt/veil/forms/settingsfaq.ui
src/qt/veil/forms/settingsfaq12.ui
src/qt/veil/settings/settingsfaq.cpp
src/qt/veil/settings/settingsfaq.h
src/qt/veil/settings/settingsfaq12.cpp
src/qt/veil/settings/settingsfaq12.h
veil-qt.files

Adding a new section to the FAQ that describes how to lock/unlock the wallet using the GUI.
closes #612

[GUI] Adding new wallet lock/unlock tab to FAQ.

---

src/chainparams.cpp

Users can't synch to the network without an existing peers.dat file, or using addnodes.
The hardcoded seed nodes in the core code have all gone offline, and needed to be refreshed.
The solution is multi-fold.  The bulk was re-porting bitcoin-seeder to veil, and making a number of improvements and fixes to the code.  We have taken that on and have a new repo to manage the Veil-DNS-Seeder; which will evolve over time.  That can be found https://github.com/Veil-Project/Veil-DNS-Seeder
The DNS Seeder is a lightweight nameserver that also talks on the veil p2p network to scrape the existing nodes, and curate them before serving them out as responses to a DNS query for the seeder name.    In the core code, both trusted full nodes, and dns seeders can serve as the seeder nodes; since the design …

[Network] Update seed nodes

---

src/qt/forms/overviewpage.ui
src/qt/forms/sendcoinsdialog.ui
src/qt/forms/sendcoinsentry.ui
src/qt/veil/forms/sendconfirmation.ui
src/qt/veil/forms/settingsadvanceinformation.ui
src/qt/veil/forms/settingsadvancenetwork.ui
src/qt/veil/forms/settingsfaq02.ui
src/qt/veil/forms/settingsfaq03.ui
src/qt/veil/forms/settingsminting.ui

v1.0.4.7 build generates several QT warnings relating to duplicate names.
The names are duplicate; for example:
```
qt/forms/overviewpage.ui: Warning: The name 'verticalLayout_3' (QVBoxLayout) is already in use, defaulting to 'verticalLayout_31'.
qt/forms/sendcoinsdialog.ui: Warning: The name 'frame' (QFrame) is already in use, defaulting to 'frame1'.
qt/forms/sendcoinsentry.ui: Warning: The name 'frame' (QFrame) is already in use, defaulting to 'frame1'.
qt/veil/forms/settingsadvancenetwork.ui: Warning: The name 'horizontalLayout_2' (QHBoxLayout) is already in use, defaulting to 'horizontalLayout_21'.
qt/veil/forms/settingsadvancenetwork.ui: Warning: The name 'label_2' (QLabel) is already in use, defaulting to 'label_21'.
qt/veil/forms/settingsadvancenetwork.ui: Warning: The name …
```

[Build] Qt duplicate name warnings corrected

---

src/veil/zerocoin/ztracker.cpp
src/veil/zerocoin/ztracker.h

The following segfault occurred on a node running veil. This is a potential fix to this segfault
```
[Thread 0x7ffef37fe700 (LWP 36705) exited]
[New Thread 0x7ffef37fe700 (LWP 36914)]
[Thread 0x7ffef37fe700 (LWP 36914) exited]
[New Thread 0x7ffef37fe700 (LWP 37562)]
[Thread 0x7ffef37fe700 (LWP 37562) exited]
[New Thread 0x7ffef37fe700 (LWP 38217)]
[Thread 0x7ffef37fe700 (LWP 38217) exited]
double free or corruption (fasttop)
Thread 26 "veil-httpworker" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fff98ff9700 (LWP 45833)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51        ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) backtrace
#0  0x00007ffff2f22e97 in __GI_raise (sig=sig@entry=6)
at ../sysdeps/unix/sysv/linux/raise.c:51
#1 …
```

Fix formatting of ztracker remove pending

---

src/prevector.h
src/serialize.h
src/test/prevector_tests.cpp

* speed up Unserialize_impl for prevector (Akio Nakamura). BTC #12324
* Gets rid of many compile warnings. (see next point)
* Lift prevector default vals to the member declaration (Ben Woosley)

Prevector: fix some compile errors. Make resize faster

---

src/miner.cpp
src/test/monthly_rewards_tests.cpp
src/validation.cpp
src/veil/budget.cpp
src/veil/budget.h
src/wallet/wallet.cpp

Code still shows veil labs, rather than veil foundation for the budget payment process.
Per @4x13:
> Where it says nLabPayment it should be changed to nFoundationPayment so there aren't any future confusions
Defunct Labs had not been changed to Foundation
Done via script:
```
git grep -lz 'LabPayment'  | xargs -0 sed -i '' -e 's/LabPayment/FoundationPayment/g'
git grep -lz 'strLabAddress'  | xargs -0 sed -i '' -e 's/strLabAddress/strFoundationAddress/g'
git grep -lz 'labScript' | xargs -0 sed -i '' -e 's/labScript/foundationScript/g'
git grep -lz 'outLab'  | xargs -0 sed -i '' -e 's/outLab/outFoundation/g'
git grep -lz 'destLab'  | xargs -0 sed -i '' -e 's/destLab/destFoundation/g'
git grep -lz 'GetLabAddress' | xargs -0 sed -i '' -e 's/GetLabAddress/GetFoundationAddress/g'
git grep -lz …
```

[Refactor] Rename Veil Labs to Veil Foundation

---

src/qt/locale/veil_en.ts
src/qt/veil/settings/settingsminting.cpp

Build generates overflow warning in `SettingsMinting`
```
qt/veil/settings/settingsminting.cpp: In constructor ‘SettingsMinting::SettingsMinting(QWidget*, WalletView*, WalletModel*)’:
qt/veil/settings/settingsminting.cpp:77:73: warning: overflow in implicit constant conversion [-Woverflow]
ui->editAmount->setValidator(new QIntValidator(0, 100000000000, this) );
^
```
The validator value (100000000000) is greater than an integer; so it only allows an integer value to be placed.
The simple solution was to reduce the integer value to something that fits into a 32 bit integer; but that will also allow a negative number to be input.  Instead, this fix sets it to a regular expression that will require a positive digit followed by 1 to 11 other digits (allowing for the size that was allowed …

[Qt][Build] Fix Mint Zerocoin amount

---

src/validation.cpp

(Note: this is also included in #727, but may be faster to merge than the full change)
The code to prune stale tips searches frequently (every time `ProcessNewBlockHeaders()` is called). 
The bulk of the time spent in `CleanBlockIndexGarbage()` is in `IsAncestor()`.  This creates an an observed cost of about 1.3 seconds at the current block height for each time the search is done, while the `cs_main` lock is held.
The logic of the `if` statement will check `IsAncestor()` before checking if the block is contained in ChainActive.  However that check is not needed if the block is determined to be in ChainActive (due to the "if not and not" logic).   This causes IsAncestor to be run for every block in the map, where the vast majority of them don't need this check (~90% of them on startup, and …

[Performance] don't check ancestry if block is in the current chain

---

src/primitives/transaction.h
src/wallet/rpcwallet.cpp
src/wallet/wallet.cpp
src/wallet/wallet.h

`listunspent` only returns basecoin results
`listunspent` specifically skipped anything that wasn't a standard transaction (skipping CT and RingCT) and skipped zerocoin transactions.
Add support for CT, RingCT and zerocoin into `listunspent`.
- [RPC] listunspent now returns the list of all unspent transactions, rather than just basecoin.
- [RPC] listunspent now properly functions when specifying value based query options.
- [RPC] listunspent now returns unspent immature transactions, not just mature transactions.
A few different places in the code use `AvailableCoins()` to collect the unspent list of basecoins, and use other methods to collect the list of other coin  types.  To handle this, a parameter was added with a bitmask to select what coin types you would like `AvailableCoins()` to …

[RPC] correct listunspent for ct, ringct and zerocoin

---

src/rpc/rawtransaction.cpp

The RPC documentation for `sendrawtransaction` shows:
`3. useDandelion     (boolean, optional, default=false) Use dandelion protocol to broadcast transaction
`
However it's actually "true" by default.
Code review fail.
Make the actual default "false".
This is important for now, because there appears to be a problem with a segmentation fault when sending a raw transaction through dandelion.  While dandelion is being investigated, we will correct the default behavior (and since `sendtoaddress` defaults to false correctly; we will go with default false.
In the future, we will work towards changing the default to true; but for now we will correct the default to match the help.

[RPC] Fix sendrawtransaction Dandelion default

---

src/interfaces/wallet.cpp
src/veil/ringct/anonwallet.cpp
src/veil/ringct/anonwallet.h
src/veil/ringct/rpcanonwallet.cpp
src/veil/ringct/stealth.cpp
src/veil/ringct/stealth.h
src/wallet/wallet.cpp

As a precursor to working through the various strangities with sending ringCT transactions, the error logging needed drastic improvements.  Not the least of these being the plethora of cases where an RPC command returns with:
```
error code: -4
error message:
AddAnonInputs failed: .
```
The different routines were very confusing.  Some returning a boolean, some returning 0 for good and 1 for bad.  It made it very confusing and caused a number of different methods to be used to return the error message through the logging utility.  All the routines returning 0 for pass only ever returned 1 for fail, so there was no real reason for them to not be changed to bool, and the return codes reversed.  This allowed for the standard `error()` method to be able to be used (which will report the …

[RPC][Logging] First round of RingCT logging cleanup

---

src/httpserver.cpp

This is required for building with GCC 9.2.

Add missing header.

---

.travis.yml

Travis fails step 6 b of the test suite and can't get past it.
Travis scripts  have a few timer checks; to make sure there is enough time to get through the remaining tests.  The intent of these checks is to cache the progress up through test step 6, generally the build of the depends files; and have them done when the tests are restarted.  This insures there is enough time for the full build and all the tests to run.
These time checks happen at the end of step 5, and at the end of step 6a.  The first makes sure that it didn't take over 20 minutes to get up through step 5; the second makes sure that it didn't take over 30 minutes to get through step 6a.  This leaves 20 minutes to finish all testing from that point on.
The problem, however, is when the script through step 5 is > 1200 …

[Build] Fix timing issue in Travis between depends and build

---

src/qt/forms/askpassphrasedialog.ui
src/qt/forms/sendcoinsdialog.ui
src/qt/guiutil.cpp
src/qt/locale/veil_en.ts
src/qt/res/css/main.css
src/qt/sendcoinsdialog.cpp
src/qt/splashscreenveil.cpp
src/qt/veil.cpp
src/qt/veil/forms/addressesmenu.ui
src/qt/veil/forms/addresseswidget.ui
src/qt/veil/forms/balance.ui
src/qt/veil/mainwindow.cpp
src/qt/veil/settings/settingswidget.cpp

As seen in issue #684 and #697; the GUI crashes when you do things it's not expecting in the send screen.
The error path in the GUI send screen tried to write the error message to the wrong object; which triggered the crash.  A number of other things were found while it was being investigated; the code to check for no recipients wasn't proper; it would never execute since the previous error catch would catch those as well.  Many things would cause the crash:  no recipient address, no value, a basecoin recipient address...
Please note this is not a deep dive into all the problems in the send code; but was a means to enable reproduction of a different problem being investigated.  More work will go into this code when the time comes.  For now, a few improvements:
- Send page now notifies you …

[GUI] Fix sending page crashes

---

src/rpc/blockchain.cpp
src/rpc/blockchain.h

The RPC command `getblockchaininfo` only contains two values for difficulty, one for PoS and one for PoW. With the change to 3 PoW algos we need to return a difficulty value for each algo.
`getblockchaininfo` was updated to return
```
"difficulty_pow": 0,
"difficulty_randomx": 0,
"difficulty_progpow": 0,
"difficulty_sha256d": 0,
"difficulty_pos": 0,
```
Search from the chaintip backward. For each block determine the algo type and if a difficulty value > 0 have already been saved for that type. Exit the difficulty lookup once a difficultly for each block type has been found or after checking the last 1440 blocks.
Run the `getblockchaininfo` cmd via rpc or the console. Verify each difficulty matches the block explorer. You can also check the difficulty of each block with …

[RPC] Update getblockchaininfo - Add a difficulty value for each algo type

---

src/veil/ringct/rpcanonwallet.cpp

The `rescanringctwallet` command states `rescanringctwallet()` when you look at the help output:
```
~$ veil-cli help rescanringctwallet
rescanringctwallet()
Rescans all transactions in the RingCT & CT Wallets.
Examples:
> veil-cli rescanringctwallet
> curl --user myusername --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "rescanringctwallet", "params": [] }' -H 'content-type: text/plain;' http://127.0.0.1:8332/
```
It's just plain wrong.  While this was a known trivial issue, it was very low priority.  However, with the use of the bash completion caused this to start to become annoying:
```
spectre@grape:~$ veil-cli rescan
rescanblockchain      rescanringctwallet()  rescanzerocoinwallet
spectre@grape:~$ veil-cli rescanringctwallet()
```
Fix it:
```
spectre@Fortune:~$ …
```

[Trivial][RPC] Fix typo in rescanringctwallet

---

src/bench/block_assemble.cpp
src/init.cpp
src/miner.cpp
src/qt/bitcoingui.cpp
src/qt/clientmodel.cpp
src/qt/splashscreenveil.cpp
src/qt/transactiontablemodel.cpp
src/qt/walletmodel.cpp
src/rpc/server.cpp
src/scheduler.cpp
src/scheduler.h
src/test/scheduler_tests.cpp
src/test/test_veil.cpp
src/test/transaction_tests.cpp
src/torcontrol.cpp
src/validation.cpp
src/validationinterface.cpp
src/veil/zerocoin/precompute.cpp
src/veil/zerocoin/zchain.cpp
src/veil/zerocoin/zwallet.cpp
src/wallet/wallet.cpp
test/lint/lint-includes.sh

* See BTC cb53b825c26af6e628ba88d72b2000e75bedbbc6
*       Replace boost::bind with std::bind
- In `src/rpc/server.cpp`, replace `std::transform` with simple loop.
- In `src/validation.cpp`, store the `boost::signals2::connection` object and use it to disconnect.
- In `src/validationinterface.cpp`, use 2 map to store the `boost::signals2::scoped_connection` object.
* Get rid of a leak in threaded batch verify (zchain.cpp).
---
This is a maintenance patch; now that std::bind is available in the standard, we want to
use this instead of boost. That way we avoid potential issues with third party code.
Furthermore, this patch fixes a memory leak in boost::thread_group usage. We won't touch boost::thread_group for now for the sake of small incremental updates.
The C++ standard keeps evolving. …

[Refactor] Replace boost::bind with std::bind and others

---

src/validation.cpp

The PoS algorithm has a much greater potential to have several stakers submitting a valid block, even though eventually only one will end up being chosen by the consensus to be the official chain.  All others that submit a block that doesn't end up in the chain will see orphans.  These orphans reside in the memory of the core daemons until they are purged.  As a result, the number of tips (as seen with `veil-cli getchaintips`) will continue to grow until it reaches a threshold of 1000.
The code searches for stale tips frequently, and has an observed cost of about 1.3 seconds at the current block height for each time the search is done.  This would have grown slowly as the chain grows.
Code was added to Veil to clean up these tips.  Other projects have many tips in their database (one …

[Chain][Performance] Rework orphan pruning

---

src/qt/coincontroldialog.cpp
src/qt/coincontroltreewidget.cpp

GUI Coin Control crashes in a couple instances:
- When on the list of utxos (either by clicking on the line or checking the box) and then escaping, wallet crashes (Issue #660).
- When checking a UTXO 10,000 veil or larger will crash the wallet (Issue #661)
First issue, the `Key_Escape` catch in `CoinControlTreeWidget::keyPressEvent` was getting the wrong object to close.
Second issue, the Coin Control display used the `BitcoinUnits::format` method for the value; which puts whitespace in values greater than 10,000.  This was not being accounted for when converting the value of the selection to a `CAmount`.
Fix both issues.  The first by addressing the proper object; the second by using the `BitcoinUnits::parse` method to convert the amount column back to a `CAmount`.
Ideally, test against …

[GUI] Fix coin control crashes

---

src/script/script_error.cpp

There’s a typo.
Fix the typo.
* nothing, this is trivial

script: fix SCRIPT_ERR_SIG_PUSHONLY error string

---

src/qt/veil.cpp

(Commit cherry picked from #766 for fast tracking)
CaveSpectre and mimir (others?) have reported a crash on recent macOS builds.
The crash is a segmentation fault in a debug handler named DebugMessageHandler(),
at runtime, before the slash screen, or main window, is shown.
The issue has been tracked down to incorrect usage of the debug.log message handler override.
This is a part of Qt that allows us to log to debug.log, using a bypassed message handler
in the form of a callback function.
The issue is that we should not access some of the “context” information, passed in the form of
a QmessageLogContext.
If we peruse the Qt documentation:
Note: By default, this information is recorded only in debug builds. You can overwrite this explicitly by …

[GUI] Do not use Qt's debugging information in the log handler.

---

src/chain.h
src/primitives/block.cpp
src/primitives/block.h
src/rpc/blockchain.cpp
src/validation.cpp
src/veil/proofofstake/stakeinput.cpp

- Added boolean logic to manually set veil data hash to zero when needed
- Added comments explaining why this is needed
- Change the hashing function name to better describe when it is doing

Fix proof of stake veil data hash error

---

src/veil/ringct/anonwallet.cpp

Occasionally wallets with a lot of ringCT transactions will start getting `GetAnonBalance: value out of range (code -1)` errors when trying to send ringct transactions.
The algorithm that counted up the total coins available used the ringct anonwallet `isSpent()` to check if a UTXO was spent.  If it didn't think it was spent, it would count it.  This ended up drastically inflating the total coins that there were believed to be; and eventually surpassed the total supply, and thus generate the error.
The `IsSpent()` code had an error.  It pulled the outpoint from the TxSpends map, and then processed the range results to determine if it was spent, or abandoned; and would consider it not spent if it got through that whole section of code.  However, the code did not properly check the hash …

[ringct] Fix IsSpent check

---

src/qt/veil/settings/settingswidget.cpp

**Problem**
In C++ the way exceptions are used is to throw by value, and to catch by reference.
In the base there are a few instances of catch by value, which is incorrect.
**Solution**
The correct fix is to simply catch by reference.
**Testing.**
I don't expect any special testing needs to be done for this item.

Rework exceptions where reference is missing.

---

src/validation.cpp

**_Every other_** reindex fails when processing RingCT transactions.  (Issue #784 )
When reindexing, the existing RingCT transactions still exist in the wallet; therefore when you compare a RingCT transaction against the list, it's found and generates an error.  The code then rolls back and clears the transaction record, so the next reindex is successful since the record doesn't exist anymore.
As in other areas of the reindex process, some calculations are skipped since it's not a new block, but rather reindexing an existing block... so you already have some information on it.  This now skips the existence test of ringct transactions on a reindex.
It is important that you run any test twice; as the first test may not have the records in them (from being deleted on a previous reindex). …

[ReIndex] Skip RingCT TX computation during resynching

---

src/qt/coincontroldialog.cpp

**problem**
This is admittedly a small issue, but nonetheless there's a leak in the CoinControl view update when the tree mode is not enabled. As you see the CCoinControlWidgetItem gets created when there's no need for it.
I think this right, please check that I didn't miss other logic there.
**how to solve**
Move the `new CCoinControlWidgetItem` a bit further down in the proper `if (treeMode)` area.
**how to test.**
You want to go into the Wallet ->  Send ->   Coin Control at the bottom.   Toggle knobs, play with the options, nothing should crash or behave strangely.

gui: Fix leak in CoinControlDialog::updateView

---

src/script/script.h

**Problem, Cause**
* It seems that the original author of the snipped used glibc code:
https://github.com/lattera/glibc/blob/master/stdlib/abs.c
However this is undefined behaviour under certain circumstances:
https://stackoverflow.com/questions/17313579/is-there-a-safe-way-to-get-the-unsigned-absolute-value->
A relevant example can be found at :
https://godbolt.org/z/yRwtCG
This was first reported in:
https://github.com/bitcoin/bitcoin/issues/18046
**How to fix**
The solution is to add 1 instead of negating.
**How to test**

Prevent UB when computing abs value for num opcode serialize

---

src/libzerocoin/Bulletproofs.cpp
src/rpc/rawtransaction.cpp

**Problem**
It is not acceptable to add an int to a string. This will result in completely different behaviour than what is intended.
**Solution**
The simple way to fix this is std::to_string() invocation to create a string object and then the plus works as intended.
Furthermore, this fixes a bug where the ? Operator has a lower priority as +.
**Testing.**
~Check that the signrawtransaction rpc command’s help message is okay.~
Open to ideas on how to test Bulletproofs::splitIntoSets.
The basic idea is sound, demonstrated by the following snipped:
```c++
#include <stdexcept> 
  
int main() 
{ 
   int s = 10; 
    (A)  throw std::runtime_error("wrong number " + s); 
    (B)  throw std::runtime_error("wrong number " + std::to_string(s)); 
   return 0; 
}
```
-----
(A)
```bash
phil@crn …
```

Correct incorrect usage of string arithmetic.

---

src/Makefile.qt.include
src/qt/macdarkmode.h
src/qt/macdarkmode.mm
src/qt/veil.cpp

Recent macOS releases have introduced a so-called “Dark Mode” feature meant to give mac users an alternative theme for their operating system.
As of this time, the stylesheets we have in the Qt application do not work well with this change of colours.
In other words:
The root cause is a change in the Qt styling system on macOS, broadly speaking the problem was introduced by Apple Inc.
The way I fix this is by just enforcing the known-good Aqua style.
In other words:
Build on a relatively recent version of macOS, and see if: 
1)  The build is successful.
2)  The user succeeds in launching the application to the main window.
3)  The main window is visible and usable.
Versions to test :  10.14, 10.13.   The former introduced the problem, check for regression on later.

Disable Dark Mode on recent versions of macOS.

---

src/Makefile.am
src/compat/stdin.cpp
src/compat/stdin.h
src/veil-cli.cpp

This PR aims to improve the cli program by bringing in hidden password input.
We don’t want to show passwords in clear text.
Bring in two commits from Bitcoin upstream.
One introduces the stdin interfaces, the other to patch in -stdin* interfaces.
1)  The build is successful.
2)  Test veil-cli with the following flags, in random combinations thereof:
→ -stdin
→ -stdinrpcpass
→ -stdinwalletpassphrase
3)  Is the behaviour acceptable?

Improvement: Password input

---

src/veil/ringct/anonwallet.cpp
src/veil/ringct/anonwallet.h
src/veil/ringct/rpcanonwallet.cpp
src/veil/zerocoin/ztracker.cpp
src/veil/zerocoin/ztracker.h
src/wallet/wallet.cpp
src/wallet/wallet.h

`getbalance` only returns the basecoin balance, and not the full balance.
It was never integrated with the other coin types.
Originally thought the anonwallet GetBalance() would be a simple fix, but it doesn't recognize zerocoin mints as spent, and only handles basecoin as well.  That should be addressed or removed from the code.  The original GetBalance() in wallet.cpp was renamed to GetBasecoinBalance() and GetBalance() was re-written to collect up the different balances.  Changes were made to the other balance code to allow for a min_value to be entered.
This affects both `getbalance` and `getwalletinfo`.  getbalance will now return the total balance in the wallet; this may be different then `getspendablebalance` if there are immature or unconfirmed balances.   Compare the output of …

[RPC] Fix getbalance to get all coin types

---

src/qt/coincontroldialog.cpp

Coin Control does not display all RingCT TXOs.
An errant check in the Coin Control code was removing RingCT transactions from the coin control list that were zerocoin mints.  This resulted in RingCT change from a minting transaction from being listed in coin control.
Remove the zerocoinmint check in the coin control check.
Test against all coin types (basecoin, stealth, ringct) after minting from each coin type [including using the 'true' flag to mint from basecoin].  After all is mature, compare total balance for each coin type in coin control (by using 'select all') against the balance from `getbalances` and ensure they match.

[GUI] Fix RingCT Coin Control for minted change

---

src/wallet/rpcdump.cpp

Dump wallet output referenced Bitcoin
leftover bitcoin reference
Fix the reference and check the file for others (which there were)
doublecheck:
- the help documentation for `importaddress`, `dumpwallet` and `importmulti`
- the contents of `dumpwallet`
- using invalid addresses in `importaddress` and `dumpprivkey`

[Trivial] Cleanup old bitcoin text

---

src/rest.cpp
src/rpc/blockchain.cpp
src/rpc/blockchain.h

**Problem**
We can remove a global lock in a few places related to the blockToJSON and blockheaderToJSON commands, for performance reasons we do not want to hold the lock cs_main if there is no need for it.
**Solution**
Get the confirmed blocks without referring to the main chain if we already have the information for it.
**Testing.**
RPC commands **getblock** and **getblockheader** must return the same values.

Getblock: do not hold cs_main.

---

src/chainparams.cpp
src/chainparams.h
src/consensus/tx_verify.cpp
src/interfaces/wallet.cpp
src/libzerocoin/SerialNumberSoK_small.cpp
src/miner.cpp
src/rpc/blockchain.cpp
src/script/ismine.cpp
src/script/standard.cpp
src/txdb.cpp
src/validation.cpp
src/veil/mnemonic/mnemonic.h
src/veil/ringct/anon.cpp
src/veil/ringct/anonwallet.cpp
src/veil/ringct/rpcanonwallet.cpp
src/wallet/rpcwallet.cpp
src/wallet/wallet.cpp
src/wallet/wallet.h

Build warnings were starting to get a little overbearing, and inducing the ignoring of warnings; Which bit me in one of the things I was tweaking.
Various, but primarily because devs tend to ignore warnings
Address them
```
In file included from consensus/tx_verify.cpp:28:0:
./veil/zerocoin/lrucache.h: In instantiation of ‘void LRUCacheTemplate<K, V>::set(K, V) [with K = std::__cxx11::basic_string<char>; V = bool]’:
consensus/tx_verify.cpp:260:69:   required from here
./veil/zerocoin/lrucache.h:57:37: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
if (keyValuesMap.size() > csize) {
miner.cpp: In member function ‘std::unique_ptr<CBlockTemplate> BlockAssembler::CreateNewBlock(const CScript&, bool, bool, bool)’:
miner.cpp:249:32: warning: comparison …
```

[Build] Clear Build Warnings

---

.github/workflows/build-factory.yml

**_With significant work by @akshaynexus in PR #783 .  Re-pushed due to rebasing challenges._**
Travis limitations makes it's ability to serve as a Continuous Integration tool ineffective; needing frequent restarts (2-3 passes) to get through a full validation build via it's caching mechanism.
Limitations of time cause us to have to exit to preserve the cache rather than timing out.  This makes it near impossible to get a clean build due to the length of time the build takes.
Migrate to github actions, which have much higher limits and much better incorporated into github.  Initially this will build for the 64 bit platforms (x86 Linux, ARM Linux, Windows and OSX).  32 bit platforms will be added on a subsequent PR.
As it's CI, it tests itself.  The completed images will need to be …

[Build] Created Github Actions CI for Veil

---

src/chainparams.cpp
src/pow.cpp

(description by CaveSpectre, take with a grain of salt)
Difficulty calculations are based on the spacing between the last X blocks of the algorithm, and does not take into account if the next block for that algo is overdue.
Refine logic to consider the spacing between the tip and the last algo block, if overdue, and adjust calculated spacing accordingly.

Update PoW Diff to use last blocktime

---

src/qt/veil/forms/settingsminting.ui

Displayed text on the 'Zerocoin minting' page is cutoff.
The height of the textlabel shrinks below the height of its content.
Adjust the `stretch` factor.
Resolves #738
`sv1qqp0j5cm6vrrkvkajpnq39gczt09eclw5z8h2zrmvrwndw7ppqaa28spqfqmkpana500t0jmjnhcjekg0rgt9jfll3w03m46p7ard9lqrpxduqqqe9a2qv`
1. Click Settings
1. Click Zerocoin minting

[GUI] Adjust stretch factor Zerocoin minting page

---

src/miner.cpp
src/miner.h

Build issued warnings for the three constant strings added.
Should be const char rather than char
correct them.

[Build] Remove constant string warnings

---

src/rpc/blockchain.cpp
src/rpc/blockchain.h

There is no RPC that would return the block count breakdown per algo. 
New algorithms were added for ProgPow, RandomX, and SHA256D.
Added a new RPC command `getchainalgostats` was added to get the block count for each algo over the previous 1440 blocks.
**`getchainalgostats`**
```
{
"pos": 727,
"progpow": 476,
"randomx": 156,
"sha256d": 81,
"x16rt": 0
}
```
**`getchainalgostats help`**
```
getchainalgostats
Returns the blocks found by each algo over that previous 1440 blocks.
Result:
{ 
"pos" :     (numeric) The number of PoS blocks found in the previous 1440 blocks 
"progpow":  (numeric) The number of ProgPow blocks found in the previous 1440 blocks 
"randomx":  (numeric) The number of RandomX blocks found in the previous 1440 blocks 
"sha256d":  (numeric) The number of SHA256D blocks …
```

[RPC] Add RPC command 'getchainalgostats' to get block count for each algo

---

src/chainparams.cpp
src/pow.cpp

The `nActualTimeSpan` is at risk of overflowing if parameters are changed (hash limit, nDgwPastBlocks, etc).  While the Actual Time Span is railed to 3x of the Target, when you multiply the difficulty hash by the number of seconds between the first and last in the series, it can easily exceed the uint256 boundary if parameters aren't carefully calculated during changes in the future.
Instead of multiplying the bnNew by the actual; which can be exceeded with parameter changes... we will divide the Actual by the Target, which have already been railed and result in a bnNew multiplier from 1/3 to 3; thus greatly reducing the chance of an inadvertent overflow

[PoW] Reduce overflow risk

---

src/crypto/hash-ops.h
src/crypto/rx-slow-hash.c

Build issued warnings for 4 routines implicitly declaration.
Implicitly declared routines need to be declared.
declare them.

[Build] Fix Implicit Declaration Warnings

---

src/crypto/randomx/randomx.cpp
src/pow.cpp
src/validation.cpp

Some lingering stdout messages come to the terminal when running the wallet in the background
Clean them up (one relating to invalidating blocks, one relating to the randomx vm cache.

[Trivial] Cleanup lingering stdout messages

---

src/chainparams.cpp
src/pow.cpp

mainnet parameters weren't aligned with the devnet settings, especially related to block spacing
With ProgPow targetting a separation of 86 seconds, RandomX every 300 and Sha256 every 600 seconds; the result would be a 70/20/10 split, rather than the intended 35/10/5 split:
Align with devnet parameters:

[PoW] Align difficulty and spacing for mainnet

---

src/index/txindex.cpp
src/index/txindex.h
src/util.h
src/validation.cpp
src/validation.h
src/veil/zerocoin/zchain.cpp
src/veil/zerocoin/zchain.h

Synching the 1.1.0 devnet chain generates many "ERROR: FindTx: txid mismatch" errors to the debug log file.
For PoS blocks, when validating the blocks, if it's a zerocoinSpend, the validation code checks to make sure the serial hashes aren't already in the blockchain [e.g. already spent].  This check is an inverse logic check from normal use, as it expects it to not be found.  However, eventually it gets down to FindTx() and generates the error message, which is to be expected.  However it's very confusing when looking at your log.
Add an optional parameter to the call structure, to pass down a logging variable to FindTx(), to not report the lack of finding the transaction as an error.
When synching Devnet from zero, you'll see many txid mismatches.  Synching again with this fix will not …

[logging] remove FindTx txid mismatch error when expected

---

.github/workflows/build-factory.yml

Noticed aarch64 builds were failing in 1.1 branch because of a package problem.  Realized a couple of them weren't updating the packages
Fixed aarch and mac builds to update and install like the others.

[Build] Fix apt updates

---

src/pow.cpp
src/validation.cpp

Syncing from scratch results in frequent randomx proof of work failures:
```
2020-08-09T02:06:21Z AcceptBlockHeader failed to get the correct value from AcceptBlockHeader. block hash = c5ef2daa3fab86b545ad4bee9dd87abe469b79dc5fb06d711a0a6d68eaf05c60
2020-08-09T02:06:21Z CheckBlockHeader : randomx proof of work failed 6d400e4584ce7617d4cdd05b84059eef56c9ff43780fe6312d03b0627259ff67
```
The RandomX key block changes every 2048 blocks.  When checking the block headers on a sync that crosses this boundary (the chain height is less than the latest key block), `GetKeyBlock()` can use the wrong key block hash.  This is likely related to the high-hash problem from before.  However that fix disregarded a failed proof of work for randomX when the block was being checked as well.
First off; …

[PoW][RandomX] Don't check RandomX PoW until checking the block

---

src/chainparams.cpp
src/miner.cpp
src/rpc/mining.cpp
src/veild.cpp

ProgPow block creation does not have a vout address for CoinBase (block mining) rewards when setting -miningaddress to a stealth address.
The infrastructure for mining to Stealth Addresses is not present in the code at this time; it is moved to a future release.  The -miningaddress flag only applies to ProgPow, and is only used in the rpc command `getblocktemplate`, and doesn't care what type of address it is.  This allows a user to inadvertently set it to a stealth address and as such the mining reward is essentially burnt.
Disallow setting a stealth address to -miningaddress (for now).  Also add checks on startup to also double check the address for the user, so that they are getting the feedback on starting the daemon, rather than until `getblocktemplate` is run.
Also fixed a typo. …

[PoW] Disallow stealth mining addresses

---

src/rpc/blockchain.cpp
src/rpc/blockchain.h

`getblockchaininfo` reports "0" difficulty if there hasn't been a block of the type in the last day
The algorithm used looked for the last block of each type, and reported that difficulty.  The difficulties were initialized to zero, so if there wasn't any blocks found, it would use the initialized value.
Original solution was to set it to minimum difficulty if the last block of that algo wasn't found.  However, it was realized that just because a block wasn't found, doesn't mean the difficulty is minimum.  It can still be pairing down as the time stretches [in cases such as a very high hash rate miner goes offline temporarily].  So rather than `getblockchaininfo` making it's own assessment off the last difficulty used, it's been changed to tap into the current difficulty calculation done …

[RPC] Rework difficulty reporting in getblockchaininfo

---

src/veil/proofofstake/kernel.cpp
src/wallet/wallet.cpp

2020-08-19T22:51:06Z ERROR: Stake() : min age violation - nTimeBlockFrom=1597877409 nStakeMinAge=60 nTimeTx=15978774
`Stake()` checks the min age whereas the calls to it (and the coin selection) looks at the depth.  This leaves the potential for something to be considered stakeable when it really isn't; and generates annoying log messages as well as consuming resources.
Move the check up and remove the error message.  Skip the tx; but don't leave it out of the list, so if it's just a couple seconds off it may be used for staking calculations as soon as the age is met.  This is much more prevalent when the depth requirement for coins is lower and when the chain is moving faster to catch up.

[PoS] Don't try to stake txs below nStakeMinAge

---

src/hash.cpp
src/hash.h
src/miner.cpp
src/pow.cpp

Starting multiple ProgPoW threads crashes deep in the depths of the algorithm:
```
ethash::(anonymous namespace)::fnv1 (v=..., u=...) at crypto/ethash/lib/ethash/ethash.cpp:44
44              r.word32s[i] = fnv1(u.word32s[i], v.word32s[i]);
(gdb) bt
#0  ethash::(anonymous namespace)::fnv1 (v=..., u=...) at crypto/ethash/lib/ethash/ethash.cpp:44
#1  ethash::item_state::update (round=180, this=0xffffcfffbe00) at crypto/ethash/lib/ethash/ethash.cpp:203
#2  ethash::calculate_dataset_item_2048 (context=..., index=<optimized out>) at crypto/ethash/lib/ethash/ethash.cpp:245
#3  0x0000aaaaab16d350 in progpow::(anonymous namespace)::round (    lookup=0xaaaaab16b920 <ethash::calculate_dataset_item_2048(ethash_epoch_context const&, unsigned int)>, state=..., mix=..., r=62,  context=...) at …
```

Fix crash on multiple progpow threads without hack

---

src/veil/ringct/anonwallet.cpp
src/wallet/rpcwallet.cpp

There is no real handy way to see your stealth addresses
Add `listaddresses`, which will return your basecoin and stealth addresses, and your stealth change address if it has a balance.
```
$ veil-cli help listaddresses
listaddresses (type)
Lists addresses in the wallet Address Book.
Arguments:
1. "type"       (string, optional) receive - all receive addresses (default).
balances - all receive addresses with balances.
Result:
[
{
"address",  (string)  The veil address
amount,     (numeric) The amount in VEIL
"label"     (string)  The label
}
,...
]
Examples:
> veil-cli listaddresses
> curl --user myusername --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "listaddresses", "params": [] }' -H 'content-type: text/plain;' http://127.0.0.1:58812/
```
```
.$ veil-cli listaddresses
[ …
```

[RPC] Add listaddresses

---

src/wallet/rpcwallet.cpp

Wallet unlock for 0 seconds is kinda useless
Per suggestion from #659 -> have '0' set the max unlock

[RPC] Let 0 be max walletpassphrase unlock

---

src/chainparams.cpp
src/rpc/mining.cpp

Every pass through `generateBlocks` loop was trying the same hash 65535 times.
The Sha256 hashing serialization algorithm uses nNonce64; but the `generate` RPC call was incrementing `nNonce`, so it was trying all with the same value of nNonce64.
Change the code to increment nNonce64; Also check so we can detect if an nNonce64 loop expired without finding a solution [also effects progPow] so that it doesn't try to submit a bad block.

[PoW][RPC] Correct Sha256 Nonce incrementation

---

src/chainparams.cpp
src/chainparams.h
src/consensus/params.h
src/pow.cpp
src/pow.h
src/veil/proofofstake/stakeinput.cpp
src/versionbits.h

**_This PR will require another restart of devnet._**
When there isn't enough hash power to maintain desired spacing for the different PoW algorithms, the block spacing tends to extend longer than 60 seconds per block.
All the algos, PoS included, manage their difficulty adjustments based on their designed spacing.  ProgPow targets one block every 172 seconds; RandomX targets one block every 600 seconds and Sha256 targets one block every 1200 seconds.  This all together accounts for one PoW block every 120 seconds.  Combining that with PoS one block every 120 seconds; you end up with a block every 60 seconds.
However, if any of the algorithms aren't meeting their designated block creation rate; there isn't any adjustments made to other algorithms.  So taking it to an extreme, with zero …

[PoS][PoW] Refine PoS to manage overall chain spacing

---

src/pow.cpp

segfault on first generated block after genesis block
When there's only one block of a given algo, there is no "One Back", so the pIndexOneBack is null and thus calls to it's structure crash.
If there's only one of any given algo, don't use oneback even if the tip is the current algo.

[DWG] Make sure OneBack exists

---

src/veil/budget.cpp
src/veil/budget.h

Existing multisig budget address is hampered by staff changes, and is nearing critical mass.
Establish new budget committee and generate a new multisig address for the budget moving forward.
This is setup to target the superblock after the next.  If the next fork is not timed to be in the July window, we will need to adjust this PR to have a new block stamp.  As such, it should wait to be merged until we are preparing the release.

[budget] Update Multisig Budget Address

---

contrib/gitian-descriptors/gitian-linux.yml

Code changes for the 1.1.0.1 release were not compatible with the current build settings. 
Update settings
To test changes you will need to use gitian. 
Clone this repo [https://github.com/Veil-Project/docker-based-gitian-builder](https://github.com/Veil-Project/docker-based-gitian-builder)
```
git clone https://github.com/Veil-Project/docker-based-gitian-builder.git
cd docker-based-gitian-builder
sudo bash run_all.sh
```
When prompted for a repo enter
`https://github.com/codeofalltrades/veil.git`
Enter tag v1.1.0.99

[Build] Update build compatibility for 1.1.0.1 release changes

---

src/miner.cpp
src/miner.h

RandomX Hashspeed was not being displayed in the logfile when using blockcreation debugging
Technically it does; however only when you actually win a block or you get through the full 100,000 hashes without another block coming in.   The problem was, if you stopped computing because another block came in while you were computing, it would restart the hashing on the next block, before it reports the hash speed used.
Move the hash debugging to before the check if the block was already found or not.  Also a couple other tweaks made; reduce the cs_nonce critical section to minimum needed, as well as remove the hardcoded inner loop count, as that inner loop count is also used for nonce spacing.  That way if the inner loop count is changed, the nonce separation between threads is consistent and …

[PoW][RandomX] Display Hashspeed after processing

---

src/veil/ringct/anonwallet.cpp
src/veil/ringct/rpcanonwallet.cpp
src/wallet/rpcwallet.cpp
src/wallet/wallet.cpp

A Stealth Staking address isn't properly created when initially starting 1.2 on an existing chain.
Only 1.2 generated wallets were tested; not transition from existing wallets on upgrade.
Added `getstealthstakingaddress` RPC command to see what your created staking address is
Added logic to list unspent to check and display any coins in the staking address
Reworked whole creation and loading logic to handle transition from 1.1 wallet to 1.2 wallet, prior to this PR, it only worked if the wallet was generated with 1.2 and not encrypted.
- Tested transition from 1.1 to 1.2
- Tested restart of 1.2 after transition
- Tested creation of 1.2 wallet
- Tested restart of 1.2 wallet after creation
- Tested transition of an encrypted wallet 1.1 to 1.2 [and restart]
- Tested transition of a 1.2 …

[RingCT Staking] Fix creation of stealth staking address on startup

---

src/wallet/rpczerocoin.cpp
src/wallet/wallet.cpp

`listzerocoinamounts` requires a wallet to be unlocked to execute
There was a specific wallet unlocked check to prevent it's use without unlocking the wallet.
Remove the check so that the `listzerocoinamounts` RPC command will execute against a locked wallet
Generally there will be little to no change to the zerocoin implementation as we are currently in the process of phasing it out.  However this was a team backed request that was a minimal interruption, so it's being pushed.  This will  be virtually obsolete after the next fork, but it will be usable from the master branch.
It is expected to be tested and approved by members of the team, and will be skipping the code review load on the dev team.

[RPC] Remove lock check for listzerocoinamounts

---

src/wallet/rpcwallet.cpp

`generatecontinuous` help example didn't have the boolean [true false] in it.
Fix the help

[Trivial][RPC] Correct generatecontinuous help

---

src/qt/bitcoingui.cpp
src/qt/veil/forms/veilstatusbar.ui
src/qt/veil/veilstatusbar.cpp
src/qt/veil/veilstatusbar.h

A small improvement to the usability: the user often needs to see what the block time is on the current node, and it is very annoying having to open the debug console to extract this information.
The value is not visible.
Two labels have been added to the bottom status bar and connected the signal to update the block time.
`sv1qqphsvuwhk29xcn2q9gdth9x73qpm8kcktmuxyd8szl50sgt2nt47egpqwnxr83hfj7s6fnec2jr0cv5yc7r6s7nvxhd9969qrgy4cgnznwewqqqauut5m`

[GUI]: add a small indicator for the last block time on lower veil status bar

---

src/miner.cpp
src/primitives/block.cpp
src/primitives/block.h

Since the datahash is not likely to change much between blocks (other than
work refresh), we can calculate it once and reuse the value.
Average hashrate beforehand on 4core vps was 4mh, averages around 5.5-6mh with
blocks successfully solved on devnet.

Optimize hashing of internal sha256d miner.

---

src/chain.cpp
src/txdb.cpp
src/validation.h

PindexWalk->pprev assert failures occur randomly on startup
_**Note that root cause is not yet completely understood.  This is not a fix, but rather a mitigation that alleviates the risk of the problem occurring.**_
A corruption occurs occasionally in the writing of the block database, where an index no longer points to the correct block, but rather reads a different block off disk.  Usually the block read happens to be an orphan block.  It definitely is connected to writing of side chains and orphans, but the root cause is yet unknown.   This problem results in a valid block not being read from disk, so when it begins to connect the blocks together [for the staking algorithmic calculations], there is a block that doesn't have a valid previous [because it basically walks off the chain …

[DB] Data error checks and frequency changes

---

src/init.cpp

#253 - Prune mode incompatible with txindex.  
Having prune mode on can stick the user into being unable to start their wallet.  For Qt: they receive an error stating "Prune mode is Incompatible with -txindex"
The error was a little heavy handed, and rejected the use of prune mode without txindex=0.  The part of this issue that makes it important to address is that you can inadvertently end up with bPrune set in your registry on windows; making it difficult to find and remove.  There is an additional issue that implies that uninstalling your wallet will not remove the registry entries; so getting bPrune=true in your registry would be quite challenging to clear out, and likely result in support tickets.
**_Note that prune mode is unsupported and likely will result in corrupting your …

[Config] Ignore prune mode if txindex is set

---

src/miner.cpp
src/miner.h
src/pow.cpp
src/qt/veil.cpp
src/rpc/mining.cpp
src/validation.cpp
src/veild.cpp

[Problem]
#340 - `getnetworkhashps` seems to be unrelated to actual network hash
#32 - `getmininginfo` has vastly changing difficulties
[Root Cause]
As greatly discussed in #340, the `getnetworkhashps` never accurately reflected PoW vs. PoS; as if one of the blocks was a PoS block, and one was a PoW block, the average calculated would vary wildly.    Likewise, `getmininginfo` would only report on the last block, which gets even crazier with 4 different block types.
[Solution]
First was a need to get your current mining algorithm; this is a separate commit.  The original code was getting the mining algorithm only when generation was started; so the startup flag sat unused until that time.  This also had the side effect of not realizing you would be mining randomX, until you started mining, …

[RPC] Reworked getnetworkhashps with tweaks to -mine and getmininginfo

---

src/miner.cpp
src/miner.h
src/pow.cpp
src/qt/veil.cpp
src/rpc/mining.cpp
src/validation.cpp
src/veild.cpp

This is built on top of #876 and also contains a couple corrections to get the `getnetworkhashps` help.
In order to switch mining algorithms, you must shut down the wallet and restart with a new `-mine=` flag.
Never implemented
Add `setminingalgo` cli command to allow you to switch between different algorithms.  This RPC command requires you to turn off mining before issuing the command and will error if it does not work. 
```
$ veil-cli help setminingalgo
setminingalgo algorithm
Changes your mining algorithm to [algorithm].  Note that mining must be turned off when command is used.
Arguments:
1. algorithm   (string, required) Algorithm to mine [progpow, randomx, sha256d].
Result:
{
"success": true|false, (boolean) Status of the switch
"message": "text",     (text) Informational message …
```

[RPC][Mining] Add ability to switch between mining algorithms without restarting wallet

---

src/miner.cpp
src/miner.h
src/pow.cpp
src/qt/veil.cpp
src/rpc/client.cpp
src/rpc/mining.cpp
src/validation.cpp
src/veild.cpp
src/wallet/rpcwallet.cpp

This is built on top of #878 and requires code added in #877 and #878 
`generatecontinuous` can get users in trouble by not knowing what their settings will do to their resources
Add checks in `generatecontinuous`:
- Warn if RandomX is set to less than 4 threads.
- Warn if Sha256D is more than one thread less than the number of cores
- Provide ability to override the warnings with a new optional parameter
- Disallow generatecontinuous true if already running
- Rework the result of the command to provide a JSON status
```
$ veil-cli generatecontinuous true 1
{
"success": true,
"algorithm": "sha256d",
"threads": 1,
"message": "Mining started"
}
$ veil-cli generatecontinuous true 1
error code: -32603
error message:
Mining already active
$ veil-cli generatecontinuous false
{
"success": true, …
```

[RPC][Mining] Add sanity checks to generatecontinuous

---

src/miner.cpp
src/miner.h
src/rpc/mining.cpp

Users want to be able to see their current hashing speed
Extract the last calculated hashspeed and provide it in `getmininginfo`.  To note, this only pulls the last calculation that was done, and is not a real-time pull.  It will be the average from the start of mining to the last calculation, from the time the first `generatecontinuous true` was run.  In other words, this will take into account any 'breaks' taken in mining.  e.g. if you have a script that turns off mining for a certain time; the hash speed calculations are still being run; and the break will be calculated into your overall hash rate.
Logic was added to `setminingalgo` to reset the statistical counters.  So after `setminingalgo` is issued, the statistics will restart on the next `generatecontinuous`.  This can be used to …

[RPC][Mining] Extract last Hashspeed calculation

---

src/qt/bitcoingui.cpp
src/qt/veil/veilstatusbar.cpp
src/qt/veil/veilstatusbar.h
src/veil/mnemonic/mnemonicwalletinit.cpp
src/wallet/rpcwallet.cpp

The staking slider does not always indicate the present state of staking.  There is a delay between when staking is enabled/disabled and when the actual enabling/disabling takes place.
The Qt indicates the state that the wallet is in.  Some amount of time is required to ensure that the state change has taken affect.  Additionally, staking is not performed while syncing.  When the user initially opens the user interface, staking is displayed as active while syncing.  Staking is initially active but will not be performed until syncing is complete.
* Text for the staking slider now shows the current state of actual staking (enabled, disable, disabled for sync, enabling ..., disabling...).
* The staking slider is disabled (cannot be changed) until syncing is complete.
* Once synchronization …

[GUI] Update Staking Slider to be reflective of status

---

src/qt/veil/veilstatusbar.cpp

A one-word correction suggested by a user.
Sorry, I should have prefixed this title with "Trivial: ". I wonder if I edit it, I wouldn't want to trigger Github Actions again.

Trivial: Update veilstatusbar.cpp

---

src/qt/bitcoingui.cpp
src/qt/bitcoingui.h
src/qt/veil/addresseswidget.cpp
src/qt/veil/addresseswidget.h
src/qt/veil/balance.cpp
src/qt/veil/balance.h
src/qt/veil/forms/balance.ui
src/qt/veil/forms/receivewidget.ui
src/qt/veil/receivewidget.cpp
src/qt/veil/receivewidget.h
src/qt/walletframe.cpp
src/qt/walletframe.h
src/qt/walletview.cpp
src/qt/walletview.h

Selection of an address on the Address Book page does not update the QR codes on the receive page or the left hand side.
Selection of an address on the Address Book page is isolated to the address book.
Notify the other displays to allow for updates based on the selection of an address.  The update includes displaying address, QR code, name (if any).
250: https://github.com/Veil-Project/veil/issues/250
136: https://github.com/Veil-Project/veil/issues/136

[GUI] Update QR Code on address selection

---

src/pow.cpp

The RandomX miner is running in light mode.
This issue was reported by a third party developer who also decided to submit the patch himself, through Strontium.
Need explanation 
`sv1`
How to test?

[Miner][Randomx] Optimised RandomX for each machine

---

src/miner.cpp
src/rpc/mining.cpp

The wallet sometimes still takes a while before it actually shuts down when mining; this is most prevalent when the mining has been shutdown before the wallet is shut down.
The wallet will have to abort the mining generation loops when shutdown is active
Add checks in the mining loops to abort when necessary

[Wallet] Reduce shutdown delays when mining

---

src/crypto/randomx/aes_hash.cpp
src/crypto/randomx/aes_hash.hpp
src/crypto/randomx/allocator.cpp
src/crypto/randomx/argon2_core.c
src/crypto/randomx/blake2/blake2.h
src/crypto/randomx/blake2/blake2b.c
src/crypto/randomx/intrin_portable.h
src/crypto/randomx/jit_compiler_a64.hpp
src/crypto/randomx/jit_compiler_a64_static.S
src/crypto/randomx/jit_compiler_fallback.hpp
src/crypto/randomx/jit_compiler_x86.cpp
src/crypto/randomx/jit_compiler_x86.hpp
src/crypto/randomx/randomx.cpp
src/crypto/randomx/randomx.h
src/crypto/randomx/virtual_machine.cpp
src/crypto/randomx/virtual_machine.hpp

Keep randomx code current
Cherry picked fixes from offical randomx repo
Fix alignment for ARMv8 code  - https://github.com/tevador/RandomX/commit/9a5d504bb3e2e754ff700b8a9415f70285c93f53
Fix inconsistent class/struct usage  - https://github.com/tevador/RandomX/commit/57545d1c537a891958c0642d9b19cad57d95b874
Combined hash and fill AES loop - https://github.com/tevador/RandomX/commit/219c02e1e508bea3b14a7b38f6614d0d5897a71a
Hide tempHash from the public API  - https://github.com/tevador/RandomX/commit/3910d49b498fe974c971771ec0a48c0ef44e9196
Replace hardcoded literal with its appropriate symbol  - https://github.com/tevador/RandomX/commit/a7733de1e7aecb8a0efc101567795c7ff2bebb5f
Fix symbol collisions with blake2b - https://github.com/tevador/RandomX/commit/7567cef4c6192fb5356bbdd7db802be77be …

[PoW][RandomX] Cherry picked fixes from offical randomx repo

---

src/util.h

Changing the default automint denomination to 1000.

Change default automint denom to 1000

---

src/crypto/randomx/argon2.h
src/crypto/randomx/argon2_avx2.c
src/crypto/randomx/blake2/blake2.h
src/crypto/randomx/dataset.hpp
src/crypto/randomx/instructions_portable.cpp
src/crypto/randomx/intrin_portable.h
src/crypto/randomx/jit_compiler.hpp
src/crypto/randomx/jit_compiler_a64_static.S
src/crypto/randomx/randomx.cpp
src/crypto/randomx/randomx.h
src/crypto/randomx/virtual_machine.hpp
src/crypto/randomx/virtual_memory.cpp
src/test/randomx_tests.cpp

Keep randomx code current
Cherry picked fixes from offical randomx repo
Add a missing function to calculate a batch of hashes - https://github.com/tevador/RandomX/commit/01381ccef32da29ef4c64209980eb2b1415fc6a4
Fix symbol collisions with blake2b - https://github.com/tevador/RandomX/commit/7567cef4c6192fb5356bbdd7db802be77be0439b
Fixes for cmake build with visual studio - https://github.com/tevador/RandomX/commit/01914b49cd7845b9349598d7f3d56bfee14c92d0
Optimized Argon2 (SSSE3/AVX2) - https://github.com/tevador/RandomX/commit/900a936816e228920debb16d1044f7d9f71b2945
Fix function names for clang on Apple - https://github.com/tevador/RandomX/commit/e43267fa866c71b5bb0a4c7f6aa185012da5cd3a
virtual_memory: add MAP_JIT on macOS - https://github.com/tevador/RandomX/commit/7c172f746f94d2f98e0927d2 …

[PoW][RandomX] Cherry picked fixes from offical randomx repo - Part 2

---

src/qt/veil/balance.cpp

Clicking on the question mark icon for the Total Balance does not (consistently) result in the tooltip appearing.
The tooltip is drawn too close to where the cursor is.  
Move the origin of the tooltip to the right.  Note that the whole of the item (text and all) is the clickable to make the menu appear.  The issue only occurred when clicking the icon which was on the right end of the button.
https://github.com/Veil-Project/veil/issues/897

[GUI] Make total balance menu easier to display

---

.github/workflows/build-factory.yml

Github Action for OSX started failing
Not sure what exactly changed, but the build of the native_biplist for MacOSX started failing due to a missing ez_setup.
Since native_biplist is using python instead of python3, needed to install the python setuptools
If the PR completes all actions, it will be merged into master

[Build] Fix OSX Github Action

---

src/qt/addressbookpage.cpp
src/qt/res/css/main.css

Current (Screenshot 1 -> Screenshot 2): hovering a selection shows a blank selection due to the background and the text turning white
New (Screenshot 1 -> Screenshot 3): hovering a selection shows a grey background correctly. 
Aligns with grey #bababab used throughout the project.

[GUI] Fix: Address Book menu hover background is white and text is white

---

src/wallet/rpcwallet.cpp

`listaddresses` RPC command now handles mining addresses in the listaddresses command
Addresses issue:  #863

[RPC] Return mining addresses in listaddresses rpc command

---

src/logging.cpp
src/logging.h
src/miner.cpp

Mining code uses the `BLOCKCREATION` logging category, which includes logging about difficulty targets, staking, zerocoins, etc, making it harder to investigate mining-specific issues.
Using the `BLOCKCREATION` category for lots of different information.
Adds a new logging category `MINING` to aid debugging mining specifically
without including block template creation logs that may be noisier.
Converts most logs in BitcoinMiner and RandomXMiner to use this category
instead of `BLOCKCREATION`.
Fixes one unlikely logging statement to include the function name.
`sv1qqpswvjy7s9yrpcmrt3fu0kd8rutrdlq675ntyjxjzn09f965z9dutqpqgg85esvg8mhmyka5kq5vae0qnuw4428vs9d2gu4nz643jv5a72wkqqq73mnxr`
Tested by running and sending the command `logging [\"mining\"]` to enable.

[Logging][Mining] Add BCLog::MINING category.

---

src/qt/locale/veil_en.ts
src/qt/veil/balance.cpp
src/qt/veil/forms/balance.ui
src/qt/veil/forms/mainwindow.ui
src/qt/veil/forms/settingswidget.ui
src/qt/veil/settings/settingswidget.cpp

(Recreated branch due to commit issue)
**Existing:**
**New:**

[GUI] Capitalize First Letter in Menu Option Words

---

src/utiltime.cpp

Following the build instructions for WSL with Ubuntu 20.04 resulted in this error:
```
utiltime.cpp: In function ‘std::string FormatISO8601DateTime(int64_t)’:
utiltime.cpp:85:5: error: ‘gmtime_r’ was not declared in this scope; did you mean ‘gmtime_s’?
85 |     gmtime_r(&time_val, &ts);
|     ^~~~~~~~
|     gmtime_s 
```
Manually changing `gmtime_r` to `gmtime_s` results in a further warning because the arguments are reversed, a sign that we're building with the Windows version that the code uses when `_MSC_VER` is set.
WSL with Ubuntu 20.04 is not building with msvc but with mingw.
Use the Windows version of this code when either `_MSC_VER` or `__MINGW64__` is set.
(**Note**: I also needed to change the build command `make HOST=x86_64-w64-mingw32` to `CC_FOR_BUILD=x86_64-linux-gnu-gcc …

[Utils] Use gmtime_s with _WIN32

---

src/miner.cpp
src/miner.h
src/rpc/mining.cpp
src/test/test_veil.cpp

While mining SHA256D, the wallet periodically gets stuck, failing to stay caught up with the chain. (At the same time, the mining significantly slows down.)
Lock contention; SHA256D is very fast, completing its loop in subsecond time on a modern cpu, meaning every thread goes through lock-heavy sections of the block template creation code multiple times per second. In comparison, RandomX on the same machine takes minutes to complete its loop, usually being interrupted by the creation of a new block instead of reaching the maximal number of attempts.
Reduce lock contention on `cs_main`. The nonce setup prior to running the hashes includes grabbing `cs_main` to perform `IncrementExtraNonce`. It takes this lock to safely get the chain tip and then to safely compare the current thread's …

[Mining] IncrementExtraNonce without cs_main

---

src/logging.cpp
src/logging.h
src/miner.cpp
src/wallet/wallet.cpp

`BLOCKCREATION` is a very noisy log category. It includes DarkGravityWave logs (which are noisy), staking messages, and generic block creation logs.
Not enough log categories.
Added a new log category specific to staking. Staking-relevant messages that were previously `BLOCKCREATION` have been moved over.
None
`sv1qqpswvjy7s9yrpcmrt3fu0kd8rutrdlq675ntyjxjzn09f965z9dutqpqgg85esvg8mhmyka5kq5vae0qnuw4428vs9d2gu4nz643jv5a72wkqqq73mnxr`
Tested on win10 x64 WLS Ubuntu 20.04: built and ran unittests individually, comparing results to a previous master commit.

[Logging] Define a STAKING log category.

---

src/init.cpp
src/qt/veil.cpp
src/qt/veil/forms/settingsminting.ui
src/qt/veil/settings/settingsminting.cpp

nPreferredDenom == DEFAULT_AUTOMINT_DENOM is actually false because:
nPreferredDenom is 10
DEFAULT_AUTOMINT_DENOM is 1000
This code change just wraps the 2 nPreferredDenom inits based on if nautomindenom is set or not in the config.
The real existing issue is in veil.cpp which occurs after init.cpp and overwrites the logic in veil.cpp for nautomintdenom anyway when it pulls from QT getSettings()
Easiest way to test is to compare this code vs. existing 
use a fresh wallet or re-build/remake from code and config file nautomintdenom value is not used on initial startup
[GUI] Users that have set their desired zerocoin automint denomination via the GUI and in the veil.conf file will now find the configuration file setting is used over the GUI setting.  If the veil configuration file has an …

[Wallet] If nautomintdenom is set, prioritize its use

---

src/veild.cpp

veild doesn't shut down properly if it fails during init.
Background threads were hanging after being interrupted, because they were looking to `ShutdownRequested()`, which was only being set by `StartShutdown()` on SIGTERM.
Solution is to call `StartShutdown()` when veild fails init and goes to interrupt running threads.
#934 
Set `autospend=1` and `autospendaddress=<basecoin address>` (or make a similar error that should cause it to close with an error on startup) in your veil.conf and run veild with `-printtoconsole`.

[Core] Properly shut down veild if init fails.

---

src/init.cpp
src/wallet/wallet.cpp
src/wallet/wallet.h

`-miningaddress` is used for rpc progpow gpu mining, but ignored for in-wallet mining such as for RandomX and SHA256D.
It's just not looking at the config value when it sets up the block script.
When the wallet attempts to retrieve a mining address, prefer the configured value for `-miningaddress`, falling back to the previous address generation from the wallet keys.
Disallows stealth addresses as per current behavior validating `-miningaddress` at startup and in rpc mining.
Performs an additional safety check that the wallet actually owns the given address, falling back to a random wallet address otherwise (preserving current behavior).
#867
`sv1qqpswvjy7s9yrpcmrt3fu0kd8rutrdlq675ntyjxjzn09f965z9dutqpqgg85esvg8mhmyka5kq5vae0qnuw4428vs9d2gu4nz643jv5a72wkqqq73mnxr`
Tested on win10 x64 …

[Mining] Use -miningaddress for in-wallet mining.

---

src/qt/veil/veilstatusbar.cpp

Related to pull request: https://github.com/Veil-Project/veil/pull/913 (and mentioned there as well. This is the separated pull request)
https://github.com/Veil-Project/veil/pull/913#issuecomment-814352629

[Staking][GUI] Unlock wallet for staking dialogue on click

---

src/sync.cpp

config/veil-config.h includes `HAVE_THREAD_LOCAL`, without which `DEBUG_LOCKCONTENTION` will fail to build due to the `static_assert`.
This allows building with `./configure CPPFLAGS="-DDEBUG_LOCKCONTENTION"` without manually adding `-DHAVE_THREAD_LOCAL` (when thread_local exists, of course).
Built via `./configure --with-incompatible-bdb CPPFLAGS="-DDEBUG_LOCKCONTENTION"` on Fedora, `CONFIG_SITE=$PWD/depends/x64_64-w64-mingw32/share/config.site ./configure --prefix=/ CPPFLAGS="-DDEBUG_LOCKCONTENTION"` on WSL Ubuntu 20.04

[Trivial] Add config include for building DEBUG_LOCKCONTENTION

---

src/miner.cpp

While mining SHA256D, the wallet periodically gets stuck, failing to stay caught up with the chain. (At the same time, the mining significantly slows down.)
Lock contention; SHA256D is very fast, completing its loop in subsecond time on a modern cpu, meaning every thread goes through lock-heavy sections of the block template creation code multiple times per second. In comparison, RandomX on the same machine takes minutes to complete its loop, usually being interrupted by the creation of a new block instead of reaching the maximal number of attempts.
Increase the number of loop iterations for SHA256D. To avoid doing useless work, also periodically check for a new block to end the outer iteration early.
* Adds an additional loop inside `BitcoinMiner` for SHA256D only, which reduces …

[Mining][SHA256D] Reduce lock contention with SHA256D

---

CMakeLists.txt
src/Makefile.am
src/veil/lru_cache.h
src/veil/zerocoin/accumulators.cpp

While mining SHA256D, the wallet periodically gets stuck, failing to stay caught up with the chain, **even with #915**. (At the same time, the mining significantly slows down.)
Lock contention; the cs_main lock is held throughout critical parts of block template creation, done independently per mining thread. The intermittent stuckness appears correlated with large numbers of txins during zerocoin spend validation. This requires determining the height of an accumulator hash, which is done by searching through all the blocks in the chain starting from genesis, for every txin. My debug logs (with -debug=bench) show very consistent examples like `- Verify 646 txins: 17392.00ms (26.923ms/txin)`.
Since the height of a particular hash-denomination pair is not going to change, we can cache it. …

[Zerocoin][Validation] Cache checksum heights

---

src/wallet/rpczerocoin.cpp

exportzerocoins help gives an example with a denomination of 5; which doesn't make any sense.
```
Examples:
> veil-cli exportzerocoins false 5
> curl --user myusername --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "exportzerocoins", "params": [false 5] }' -H 'content-type: text/plain;' http://127.0.0.1:58812/
```
Tweak it to show an example of 10
```
Examples:
> veil-cli exportzerocoins false 10
> curl --user myusername --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "exportzerocoins", "params": [false 10] }' -H 'content-type: text/plain;' http://127.0.0.1:58812/
```

[RPC][Trivial] Tweak exportzerocoins example to be sensible

---

src/qt/transactionrecord.cpp

The wallet transaction list was updated to show the correct address #898 
Zerocoins sent to a bv1 address were causing the force_return error. The address format is bech32 however the decode method  was trying to decode the address as bech32 = false. 
The address format is bech32 however the decode method  was trying to decode the address as bech32 = false. 
Decode the address using the correct format.
1. Create a new wallet
2. Get a basecoin address
3. Spend Zerocoins from a different wallet to the basecoin address
4. Verfiy the tx(s) are confirmed in the new wallet
5. Restart the wallet(veil-qt) with -reindex-chainstate
6. Verify the force_return error does not occur

[GUI][Zerocoin] transaction list - handle receive from zerocoin transactions

---

src/qt/veil/addressesmenu.cpp
src/qt/veil/addressesmenu.h
src/qt/veil/addresseswidget.cpp

**Before:**
**After:**
Previous code moved the selection menu to the far top right of the screen.
Instead, the  selection menu should intuitively be right next to where you click.

[GUI] Move menu to cursor location instead of far right of the rectangle

---

src/veil/ringct/anonwallet.cpp
src/wallet/wallet.cpp
src/wallet/wallet.h

tsan identifies a data race within WalletBatch, commonly between KeepKey and AddToWallet.
Declare CWallet::KeepKey as requiring `cs_wallet`, and take it before all calls as prescribed by clang. (This moved the tsan data race to the nearby fields of CReserveKey, which was mitigated by including their access within the lock.)
Add another cs_wallet use per clang warning: AddKeyPubKey requires holding mutex 'pwalletParent->cs_wallet' exclusively.
Configured with --with-sanitizers=thread, built with clang, and run on regtest. tsan warnings for this area no longer appear.

[Wallet] Lock cs_wallet in additional places.

---

src/chainparams.cpp

Replace eg `"tv"+2` with the suggested syntax of `&"tv"[2]`.
Built veild and run with gcc, clang.

[Trivial] Placate clang warning string-plus-int

---

src/chain.cpp
src/chain.h

tsan identified a data race on CChain, particularly concurrent access to the underlying vector's `operator[]`, `size`, and `resize` member functions.
Create a new lock `cs_vchain` and mark `vchain` as guarded by it, and ensure that the lock is taken prior to any use.
For the `operator==` member function, grab both the locks in a prescribed order to avoid a deadlock.
Configured with --with-sanitizers=tsan, built with clang, run on regtest with 2 SHA mining threads enabled.

[Consensus] Add locking on the chain index vector.

---

src/sync.cpp
src/sync.h

By changing the type of the lock from void* (which has no capability) to the actual type (which does).
(Templates more or less have to be defined in a header, included in a header, or specializations explicitly declared in a header, so the actual implementation here is to call the original function that took a void*.)
Built and run veild/veil-cli with clang. Built veild/veil-cli with clang with `-DDEBUG_LOCKORDER`.

[Utils] Templatify AssertLockHeld to placate clang warning

---

src/txdb.cpp

Previously, it was logging "Block 2: ..." when 2 was the status, which is fairly misleading. Now, output both the height and the status and make clear which is which.
Mildly, during my other regtest runs, and startup for testnet.

[Logging] Improve hash mismatch warning log message.

---

src/crypto/sha256_shani.cpp

This is a cherry-pick of https://github.com/bitcoin/bitcoin/pull/18553 fixing https://github.com/bitcoin/bitcoin/issues/18456 which suddenly cropped up on my linux 18.04 machine.
Certain linux configurations may encounter a `SIGILL` Illegal Instruction that causes a locally-built veild to crash immediately. Using gdb to catch the stack trace will give a reference to global variable initialization in the sha256_shani.cpp file. Root cause appears to be a global constant is not produced correctly by the compiler as a constant.
Cherry-pick bitcoin's solution to the same problem.
Verified that veild (regtest) is now able to run on the machine where this issue occurred.

Avoid non-trivial global constants in SHA-NI code

---

src/interfaces/wallet.cpp
src/miner.cpp
src/rpc/blockchain.cpp
src/wallet/rpcwallet.cpp
src/wallet/wallet.cpp

Building with clang results in lots of warnings about lock annotations not being obeyed.
Follow instructions on warnings:
- Replace double lock of cs_main with an assertion.
- Reorganize code to release cs_main before calling blockheaderToJSON.
- Lock cs_main before calling any of: GetBlocksToMaturity, GetAddressBalances, IsSpent, TestBlockValidity.
Configured with --with-sanitizers=thread, built with clang, run on regtest.

[Wallet][Consensus] Resolve misc clang lock annotation warnings.

---

src/init.cpp
src/validation.cpp
src/validation.h

**Problem**
This is a refactor fix. We want to remove boost functions slowly.
**Root Cause**
**Solution**
We can work around the boost interruption point by just returning, and shutting down the program, instead. It is much cleaner than relying on boost to redirect control flow.
**Unit Testing Results**
Can be tested by calling -reindex or -loadblock and then pressing CTRL+C.
Should print something like:
> ...
> 2020-04-27T19:34:31Z [loadblk] Reindexing block file blk00005.dat...
> ^C2020-04-27T19:34:32Z [loadblk] Shutdown requested. Exit ThreadImport
> 2020-04-27T19:34:32Z [qt-init] Interrupting HTTP server
> ...
>

init: remove boost from ThreadImport.

---

CMakeLists.txt
src/Makefile.am
src/csv/CSV.hpp
src/csv/CSVread.cpp
src/csv/CSVwrite.cpp
src/csv/License_GPLv3.txt
src/csv/csv.h
src/csv/libcsv.c
src/csv/strerror.cpp
src/csv/strerror.hpp
src/utiltime.cpp
src/utiltime.h
src/wallet/rpcwallet.cpp

Add RPC `exporttransactions` to export to a CSV file, similar to the existing `listtransactions` RPC command
Added a well tested external CSV library to the project that will make future CSV functionality trivial in the future
Added the rpc `exporttransactions` command supporting an output filename; and filtering by account, date range, and/or basic piped separated search string
```
exporttransactions (dummy filename start end categories include_watchonly)
Exports transactions between 'start' date and 'end' date matching 'categories' to a CSV file.
Note: To export from a specified "account", restart veild with -depreciatedrpc=accounts and
use this RPC with an "account" argument
Arguments:
1. "dummy"      (string, optional) If set, should be "*" for backwards compatibility.
2. "filename" …
```

[Wallet][RPC] Export basecoin transactions to CSV file

---

src/chain.h
src/index/base.cpp
src/init.cpp
src/interfaces/wallet.cpp
src/miner.cpp
src/net_processing.cpp
src/qt/coincontroldialog.cpp
src/rest.cpp
src/rpc/blockchain.cpp
src/rpc/mining.cpp
src/rpc/rawtransaction.cpp
src/validation.cpp
src/validation.h
src/veil/ringct/anonwallet.cpp
src/veil/zerocoin/accumulators.cpp
src/veil/zerocoin/zchain.cpp
src/veil/zerocoin/ztracker.cpp
src/veil/zerocoin/zwallet.cpp
src/wallet/rpcwallet.cpp
src/wallet/test/wallet_tests.cpp
src/wallet/wallet.cpp

tsan identified a data race on CChainState, particularly between AcceptBlock and ActivateBestChain (used often by the miner threads).
Mark `mapBlockIndex` as guarded by `cs_mapblockindex`, and ensure that the lock is taken prior to any use. Some code has been reorganized slightly to reduce the time spent holding the lock and avoid locking a second time for the same information.
Move many lookups to use LookupBlockIndex, which grabs the lock itself, and remove lots of cs_main uses that would have otherwise blocked only for LookupBlockIndex.
Original: Configured with --with-sanitizers=tsan, built with clang, run on regtest with 2 SHA mining threads enabled.
With cs_mapblockindex: configured --with-sanitizers=tsan, built with clang, run on testnet to catch up and mine 2 sha threads.

[Consensus] Protect mapBlockIndex with its own mutex

---

src/libzerocoin/bignum.h

Here is a patch regarding a few issues with the way arith_uint256 is used.
The constructor is called directly to set the initial value, and there's a typo in the name of a class.

arith: fix some constructor issues.

---

configure.ac
depends/packages/boost.mk
doc/build-osx.md
src/qt/macdarkmode.mm
src/qt/macdockiconhandler.mm
src/qt/trafficgraphwidget.cpp
src/qt/veil.cpp

Push Summary
Fix compilation issue on MacOS 10.15 Catalina machine.
Root Cause
Changes in XCode 11 Objective-C Runtime caused an error building on
MacOS 10.15 Catalina machine.  
Updated instruction on how to build berkeley DB for macOS 10.15 Catalina.
Solution
Ported solution from bitcoin PR 16720.
Bounty PR
Bounty Payment Address
sv1qqp6aptgvgp9t9h8sgzkqmu6cgq2e20l9x6fsl5ask7t3ygy2jagftcpq0x5z0h522ca5h06qq3hx33pke00r7gjt3j24n896gf55y68ptrmjqqqqd8lz3
Unit Testing Results

Fix errors compiling for OSX catalina

---

src/chain.cpp
src/chain.h
src/validation.cpp

Pruned blocks sometimes cause other blocks in the index (mostly descendants of orphans) to have invalid parents, which may trip an assert `pindexWalk->pprev` (#692) on startup. Additionally, because block indexes *don't own their own hash values*, removing the index from `mapBlockIndex` where the hash is allocated may lead to a use-after-free corrupting the hash of a block written to disk (may be the cause of https://github.com/Veil-Project/veil/issues/930#issuecomment-819166828).
Select pruning candidates in two rounds: first, based on height. Then, add all descendants of the blocks chosen in the first round.
For the memory issue, add a `shared_ptr` field to CBlockIndex that provides the hash value when the block is removed from mapBlockIndex. This will manage the memory of the hash for …

[Chain] Prune entire orphaned chains.

---

src/chain.cpp
src/chain.h
src/txdb.cpp
src/validation.cpp

Issue #942:
Orphaned blocks sometimes had inconsistent hashes between block index hash (generally the cached value) and the disk index hash (produced by taking a new hash of the data). On closer inspection, `hashAccumulators` was the only differing value.
Make sure `hashAccumulators` is set or copied appropriately where relevant, particularly when `mapAccumulatorHashes` is set but not changed. The main culprit is likely `LoadBlockIndexGuts`, since it would be very easy to forget to update `hashAccumulators` before writing it out again.
Plus we use `hashAccumulators` instead of recalculating the map's hash as described in #942.
On regtest, with lots of extra debug warnings in `WriteBatchSync` about bad hashes, minted zerocoins in forks, confirmed this makes the debug warnings go away.

[Chain] Keep hashAccumulators more up-to-date.

---

src/veil/lru_cache.h

Initialize the `keyValueMap` directly from `s` instead.

[Trivial] Fix clang warning: 'csize' not initialized.

---

src/miner.cpp
src/miner.h
src/rpc/mining.cpp

In `getmininginfo`, it isn't clear that it computes the `hashspeed` by counting all hashes made since the start of hashing and dividing by the elapsed time, which tends to smooth out fluctuations but also (prior to #966) can include periods of time when the miner is off or the number of threads different.
This adds a field to `getmininginfo` called `hashspeed_recent` which is a sum of each thread's most recent round of hashing (where a round is either a fixed number of hashes or ends with a new block).
On regtest chain with sha256d and randomx.

[Mining] Recent mining hash speed

---

src/wallet/rpcwallet.cpp

This is similar to another call, just somehow missed this one earlier.

Lock cs_main before calling GetBlocksToMaturity

---

src/veil/proofofstake/stakeinput.cpp

Extracts some likely reusable code from ZerocoinStake, and moves the
helper functions to the top of the file.

[Refactor] GetStakeModifier

---

src/veil/mnemonic/dictionary.h

This was the only one necessary to build veild. I imagine any others have a `using` directive somewhere in their includes.

[Trivial] Fix a size_t reference for clang 13

---

src/rpc/blockchain.cpp

Current implementation always performs a subtraction `ins - outs` to calculate fee, which is only correct for basecoin-to-basecoin, and results in zerocoin spends appearing as the fee. CT/RingCT and Zerocoin Minting/Spending include a ct_fee output that we can use (ZC spends have a ct_fee of 0 but at least that lets us skip the subtraction).

[RPC] Correct getblockstats fee calculation

---

src/Makefile.am
src/veil/ringct/receipt.cpp
src/veil/ringct/receipt.h
src/veil/zerocoin/spendreceipt.cpp
src/veil/zerocoin/spendreceipt.h

This makes it easier to organize multiple transactions into a single receipt regardless of whether it's a zerocoin spend or something else. (#970)

[Refactor] Split ZerocoinSpendReceipt into a generic Receipt.

---

src/consensus/tx_verify.cpp
src/consensus/tx_verify.h
src/validation.cpp
src/veil/ringct/anonwallet.cpp
src/veil/ringct/anonwallet.h

Creating multiple ringct spend transactions in a batch (as part of #970) does not work because of these two similar issues.
1.  When creating a transaction, the transaction record has dummy inputs which don't correspond to any actual output, so we don't actually track the pending spends.
2.  When verifying that we aren't double-spending any ringct output, we add every keyimage we see to the set to check against. But if we're testing that a transaction could be accepted to the mempool, then committing that transaction, the commit fails (until the next block).
1.  Extract the spent coins' txo records to be marked as pending spend.
2.  Don't track the inputs permanently when testing that a transaction could be accepted to mempool. We still track within the transaction.
On regtest with other …

[Consensus][RingCT] Correctly track and test RingCT spends.

---

src/veil/ringct/anonwallet.cpp
src/veil/ringct/anonwallet.h

Rearranges part of `AddAnonInputs_Inner` into separate helper functions so it's easier to understand and also to reuse the code elsewhere. I'm not sure I fully understood the code enough to properly name the helper functions, but here they are:
* ArrangeBlinds
* Places the real inputs and creates dummy entries for the ring.
* Optionally adds temporary dummy sigs.
* GetKeyImage
* Attaches the key image for a real input.
* I made this take one at a time for ease of calling from elsewhere.
* SetBlinds
* Does some further stuff to the blinds.

[Refactor] Move parts of AddAnonInputs into helper functions.

---

src/veil/ringct/anonwallet.cpp

Discovered a malformed error message during debugging. This allows the error to properly be formatted.

[Logging] Add missing format specifier.

---

src/qt/veil/forms/miningwidget.ui
src/qt/veil/miningwidget.cpp
src/qt/veil/miningwidget.h

**Problem**
Original implementation of the Mining Tab limits the user to only a number of threads equivalent to the number of cores the computer has.  This is OK for SHA256 but should be allowed to be override for other algorithms.
**Root Cause**
No option for override
**Solution**
Implement the ability to override.

[GUI|MINE] update for override of max thread usage

---

src/miner.cpp
src/miner.h
src/rpc/mining.cpp
src/util/strencodings.cpp
src/util/strencodings.h
src/validation.cpp
src/validation.h

- No external RandomX mining possible.
- Mining multiple algorithms at the same time is currently not possible.
- The algorithm `getblocktemplate` RPC uses for its blocks depends on the value the user selects for mining in the GUI of the wallet / in the config.
Not implemented yet.
The solution was to:
1. Add an `algo` parameter to the `getblocktemplate` RPC which overrides any mining algorithm specified in the config / GUI.
2. Add a new RPC `rxrpcsb` for submitting randomx blocks, analogous to `pprpcsb`.
This makes it possible to mine at the same time progpow, randomx and sha256d externally, independently of what you may additionally mine using the wallet.
?
`sv1qqpjsrc60t60jhaywj5krmwla52ska70twc7wun6qnee65guxhvtxegpqwhuxypra4jn3pq86s24ryltcw6g2ss4573hyqac9u4g23m9mvxpyqqqwny49k`
Tested …

Add RPCs for external RandomX mining

---

src/interfaces/wallet.cpp
src/veil/ringct/anonwallet.cpp
src/veil/ringct/anonwallet.h
src/veil/ringct/rpcanonwallet.cpp
src/veil/ringct/temprecipient.cpp
src/wallet/wallet.cpp
src/wallet/wallet.h

RPC send commands have a new argument `inputs_per_tx` that controls whether the amount specified can be split across multiple transactions. This value ranges from 0 (default) to 32 (an upper bound designed to prevent transactions larger than can be accepted). When set to 0, attempts to fit the send in one transaction as per previous behavior.
The sends are interpreted to mean that the recipient will receive the sent amount, but under the hood the transactions are created as if `subtractfeefromamount` was specified. In particular, if the send needs to be split into `n > 1` transactions, the outputs of the first `n - 1` are randomly reduced to account for the fee (and the shortfall from the inputs).
Coins are selected using a sliding window that prioritizes cleaning up small utxos (dust) …

[RPC][Wallet] Create multiple transactions with one command.

---

src/interfaces/wallet.cpp
src/interfaces/wallet.h
src/qt/overviewpage.cpp
src/qt/transactionfilterproxy.cpp
src/qt/transactionfilterproxy.h
src/qt/transactionrecord.cpp
src/qt/transactionrecord.h
src/qt/transactiontablemodel.cpp
src/qt/transactiontablemodel.h

* Show the PoW type for each coinbase transaction in the transaction history
* Also implement filtering the transaction history by PoW type

[GUI] Show PoW type for coinbase transactions in transactions history

---

src/qt/bitcoingui.cpp
src/qt/bitcoingui.h
src/qt/overviewpage.cpp
src/qt/transactionrecord.cpp
src/qt/transactionrecord.h
src/qt/transactiontablemodel.cpp
src/qt/transactiontablemodel.h
src/qt/walletview.cpp
src/qt/walletview.h
src/ui_interface.h
src/veil/ringct/anonwallet.cpp
src/veil/ringct/anonwallet.h
src/wallet/wallet.cpp
src/wallet/wallet.h

When receiving a CT transaction while the wallet is locked (or unlocked for staking only), the amount displayed in the transaction history is wrong, and keeps wrong until a `rescanringctwallet` rpc is called and the wallet is restarted.
- More concretely the wrong amount showed is -1 satoshi per output in the transaction, which comes from the default value in the following line: https://github.com/Veil-Project/veil/blob/7c8bee132ea6305b29a613679b7591a27d8edbd8/src/veil/ringct/outputrecord.h#L43
- Furthermore, for the case when the transaction contained a change output, there was a bug in the way the GUI calculates the transaction amount, which resulted in that default -1 satoshi also being added for the change output (which isn't owned by the receiving wallet), thus the final amount was …

Fix wrong CT / RingCT amounts in transaction history when wallet locked

---

src/veil/proofofstake/kernel.cpp
src/veil/proofofstake/stakeinput.cpp
src/veil/proofofstake/stakeinput.h
src/wallet/wallet.cpp

In preparation for defining a RingCTStakeInput type, move more zerocoin-specific stuff behind a CStakeInput interface.
Namely:
* Getting the weight of the stake coin.
* Finishing up the transaction creation (RingCT may have more to do than zerocoin here).
Also moved a variable `nCredit` that needs to be reset on each loop into the loop.
Not tested beyond compiling.

Refactor ZC-specific staking functionality.

---

src/rpc/mining.cpp

The `getblocktemplate` rpc, should always include the RandomX seed (if a RandomX template is requested) and the ProgPow epoch (if a ProgPow template is requested), also if no miningaddress was specified in the config.

[RPC] Return RandomX seed and ProgPow epoch also if no miningaddress is set

---

src/init.cpp
src/validation.cpp
src/validation.h

Stale block indexes will only occur if the chaintip gets thrashed around aggressively, or during extended periods of minting; never during InitialBlockDownload and even then this only needs to be checked periodically.
Performance increase during block synchronization is very noticeable once applied.

[Chain] Eliminate unnecessary overhead testing for stale block indexes.

---

src/qt/askpassphrasedialog.cpp

Updating the encryption warning to not seem like your in trouble or it's end of the world for protecting your coins.

Addressing Issue #1000

---

src/rpc/mining.cpp

The hashrates returned by the `getnetworkhashps` rpc were always wrong, because the calculation was based on the entire work of the chain (including all three mining algos and also proof-of-stake).
Fixes #1018

[Mining][RPC] Fix `getnetworkhashps` rpc

---

src/chain.cpp
src/pow.h

Race condition between https://github.com/Veil-Project/veil/blob/4107c99a2029a07f89ad0b1e0f68c03ec55b7350/src/pow.cpp#L462 and https://github.com/Veil-Project/veil/blob/4107c99a2029a07f89ad0b1e0f68c03ec55b7350/src/chain.cpp#L304
which use the same RandomX VM but the first one correctly acquires the lock `cs_randomx_validator` before, while the second doesn't acquire the lock.
This bug caused the daemon / wallet to randomly crash.

Bugfix: race condition of two threads using same RandomX VM

---

src/qt/veil/forms/settingsminting.ui
src/wallet/wallet.cpp

This fix should have `automint` turned off by default. I have tested on mac with no issues. All the other wallet functionally seem to work with automint disabled. I have also changed the automint page to reflect the change and to help the user understand that they can still mint to the right of the page like always. As well as from the debug console.

Issue # 943 automintoff by default

---

src/qt/overviewpage.cpp

To open a URL in a browser, setOpenExternalLinks for label_3 must set to true.

[GUI] Fix veil.tools hyperlink in wallet

---

.github/workflows/build-factory.yml

Added riscv64 build step to github actions (without veil-qt).
Tested on visionfive 2 board

[Github actions] RISCV64

---

.github/workflows/build-factory.yml

[Github actions] Updated actions

---

depends/packages/qt.mk
depends/patches/qt/fix_limits_header.patch
src/support/lockedpool.cpp
src/veil/mnemonic/mnemonic.h

These changes were required on my machine.
Add include for std::runtime_error, and add include for uint8
Additionally this adds a patch for Qt that adds some limits stuff like std::max.

Fix compilation under gcc 13
